In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\krthg\appdata\local\programs\python\python39\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\krthg\appdata\local\programs\python\python39\lib\site-packages (from selenium) (1.26.6)

WARNING: You are using pip version 21.2.1; however, version 21.2.4 is available.
You should consider upgrading via the 'c:\users\krthg\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

In [2]:
import pandas as pd
import os
import warnings
warnings.filterwarnings("ignore")
from selenium import webdriver
from selenium.webdriver.support.ui import Select
import time
pd.set_option('display.max_rows',None)

In [3]:
os.chdir(r"C:\Users\krthg\OneDrive\Documents\Merit\PythonAssignments")

In [4]:
testbatrankings = []
odibatrankings = []
t20batrankings = []
testbowlrankings = []
odibowlrankings = []
t20bowlrankings = []
testallrankings = []
odiallrankings = []
t20allrankings = []
testteam = []
oditeam = []
t20team = []

In [7]:
driverPath = r"C:\Users\krthg\OneDrive\Documents\Merit\PythonAssignments\Webdriver\chromedriver.exe"
driver = webdriver.Chrome(executable_path=driverPath)
driver.get("https://www.cricbuzz.com/")
time.sleep(1)
driver.find_element_by_xpath("//div[@id='rankingDropDown']").click()
driver.find_element_by_xpath("//a[@id='batsmen-tab']").click()
Testrankings = driver.find_elements_by_xpath("//a[@id='batsmen-tests-tab']//following::div[contains(@class,'cb-col cb-col-100 cb-font-14 cb-lst-itm text-center')]")
for i in Testrankings:
    if i.text != '':
        testbatrankings.append(i.text.split("\n"))
print(testbatrankings) 
driver.find_element_by_xpath("//a[@id='batsmen-tab']").click()
driver.find_element_by_xpath("//a[@id='batsmen-odis-tab']").click()
Odirankings = driver.find_elements_by_xpath("//a[@id='batsmen-odis-tab']//following::div[contains(@class,'cb-col cb-col-100 cb-font-14 cb-lst-itm text-center')]")
for j in Odirankings:
    if j.text != '':
        odibatrankings.append(j.text.split("\n"))
print(odibatrankings)
driver.find_element_by_xpath("//a[@id='batsmen-tab']").click()
driver.find_element_by_xpath("//a[@id='batsmen-t20s-tab']").click()
T20rankings = driver.find_elements_by_xpath("//a[@id='batsmen-t20s-tab']//following::div[contains(@class,'cb-col cb-col-100 cb-font-14 cb-lst-itm text-center')]")
for k in T20rankings:
    if k.text != '':
        t20batrankings.append(k.text.split("\n"))
print(t20batrankings)

# Bowling rankings

driver.find_element_by_xpath("//a[@id='bowlers-tab']").click()
driver.find_element_by_xpath("//a[@id='bowlers-tests-tab']").click()
Testbowlrankings = driver.find_elements_by_xpath("//a[@id='bowlers-tests-tab']//following::div[contains(@class,'cb-col cb-col-100 cb-font-14 cb-lst-itm text-center')]")
for i in Testbowlrankings:
    if i.text != '':
        testbowlrankings.append(i.text.split("\n"))
print(testbowlrankings) 
driver.find_element_by_xpath("//a[@id='bowlers-tab']").click()
driver.find_element_by_xpath("//a[@id='bowlers-odis-tab']").click()
Odibowlrankings = driver.find_elements_by_xpath("//a[@id='bowlers-odis-tab']//following::div[contains(@class,'cb-col cb-col-100 cb-font-14 cb-lst-itm text-center')]")
for j in Odibowlrankings:
    if j.text != '':
        odibowlrankings.append(j.text.split("\n"))
print(odibowlrankings)
driver.find_element_by_xpath("//a[@id='bowlers-tab']").click()
driver.find_element_by_xpath("//a[@id='bowlers-t20s-tab']").click()
T20bowlrankings = driver.find_elements_by_xpath("//a[@id='bowlers-t20s-tab']//following::div[contains(@class,'cb-col cb-col-100 cb-font-14 cb-lst-itm text-center')]")
for k in T20bowlrankings:
    if k.text != '':
        t20bowlrankings.append(k.text.split("\n"))
print(t20bowlrankings)

# All-rounders rankings

driver.find_element_by_xpath("//a[@id='all-rounders-tab']").click()
driver.find_element_by_xpath("//a[@id='allrounders-tests-tab']").click()
Testallrankings = driver.find_elements_by_xpath("//a[@id='allrounders-tests-tab']//following::div[contains(@class,'cb-col cb-col-100 cb-font-14 cb-lst-itm text-center')]")
for i in Testallrankings:
    if i.text != '':
        testallrankings.append(i.text.split("\n"))
print(testallrankings) 
driver.find_element_by_xpath("//a[@id='all-rounders-tab']").click()
driver.find_element_by_xpath("//a[@id='allrounders-odis-tab']").click()
Odiallrankings = driver.find_elements_by_xpath("//a[@id='allrounders-odis-tab']//following::div[contains(@class,'cb-col cb-col-100 cb-font-14 cb-lst-itm text-center')]")
for j in Odiallrankings:
    if j.text != '':
        odiallrankings.append(j.text.split("\n"))
print(odiallrankings)
driver.find_element_by_xpath("//a[@id='all-rounders-tab']").click()
driver.find_element_by_xpath("//a[@id='allrounders-t20s-tab']").click()
T20allrankings = driver.find_elements_by_xpath("//a[@id='allrounders-t20s-tab']//following::div[contains(@class,'cb-col cb-col-100 cb-font-14 cb-lst-itm text-center')]")
for k in T20allrankings:
    if k.text != '':
        t20allrankings.append(k.text.split("\n"))
print(t20allrankings)

# Teams rankings

driver.find_element_by_xpath("//a[@id='teams-tab']").click()
driver.find_element_by_xpath("//a[@id='teams-tests-tab']").click()
Testteamrankings = driver.find_elements_by_xpath("//a[@id='teams-tests-tab']//following::div[contains(@class,'cb-col cb-col-100 cb-font-14 cb-brdr-thin-btm text-center')]")
for i in Testteamrankings:
    if i.text != '':
        testteam.append(i.text.split("\n"))
print(testteam) 
driver.find_element_by_xpath("//a[@id='teams-tab']").click()
driver.find_element_by_xpath("//a[@id='teams-odis-tab']").click()
Oditeamrankings = driver.find_elements_by_xpath("//a[@id='teams-odis-tab']//following::div[contains(@class,'cb-col cb-col-100 cb-font-14 cb-brdr-thin-btm text-center')]")
for j in Oditeamrankings:
    if j.text != '':
        oditeam.append(j.text.split("\n"))
print(oditeam)
driver.find_element_by_xpath("//a[@id='teams-tab']").click()
driver.find_element_by_xpath("//a[@id='teams-t20s-tab']").click()
T20teamrankings = driver.find_elements_by_xpath("//a[@id='teams-t20s-tab']//following::div[contains(@class,'cb-col cb-col-100 cb-font-14 cb-brdr-thin-btm text-center')]")
for k in T20teamrankings:
    if k.text != '':
        t20team.append(k.text.split("\n"))
print(t20team)


driver.close()

[['1', '    –', 'Kane Williamson', 'NEW ZEALAND', '901'], ['2', '    3', 'Joe Root', 'ENGLAND', '893'], ['3', '    1', 'Steven Smith', 'AUSTRALIA', '891'], ['4', '    1', 'Marnus Labuschagne', 'AUSTRALIA', '878'], ['5', '    1', 'Virat Kohli', 'INDIA', '776'], ['6', '    –', 'Rohit Sharma', 'INDIA', '773'], ['7', '    –', 'Rishabh Pant', 'INDIA', '736'], ['8', '    3', 'Babar Azam', 'PAKISTAN', '725'], ['9', '    1', 'David Warner', 'AUSTRALIA', '724'], ['10', '    1', 'Quinton de Kock', 'SOUTH AFRICA', '717'], ['11', '    1', 'Henry Nicholls', 'NEW ZEALAND', '714'], ['12', '    –', 'Dimuth Karunaratne', 'SRI LANKA', '712'], ['13', '    1', 'Ross Taylor', 'NEW ZEALAND', '693'], ['14', '    3', 'Tom Latham', 'NEW ZEALAND', '677'], ['15', '    2', 'Ajinkya Rahane', 'INDIA', '677'], ['16', '    1', 'Ben Stokes', 'ENGLAND', '677'], ['17', '    2', 'Dean Elgar', 'SOUTH AFRICA', '661'], ['18', '    2', 'Cheteshwar Pujara', 'INDIA', '658'], ['19', '    1', 'Azhar Ali', 'PAKISTAN', '658'], ['20', '    –', 'Aiden Markram', 'SOUTH AFRICA', '651'], ['21', '    –', 'Mohammad Rizwan', 'PAKISTAN', '637'], ['22', '    1', 'Mushfiqur Rahim', 'BANGLADESH', '626'], ['23', '    1', 'Travis Head', 'AUSTRALIA', '618'], ['24', '    1', 'Angelo Mathews', 'SRI LANKA', '618'], ['25', '    2', 'Tamim Iqbal', 'BANGLADESH', '605'], ['26', '    2', 'Sean Williams', 'ZIMBABWE', '603'], ['27', '    2', 'Brendan Taylor', 'ZIMBABWE', '603'], ['28', '    6', 'Rory Burns', 'ENGLAND', '600'], ['29', '    1', 'Mominul Haque', 'BANGLADESH', '596'], ['30', '    2', 'Niroshan Dickwella', 'SRI LANKA', '589'], ['31', '    2', 'Dhananjaya de Silva', 'SRI LANKA', '588'], ['32', '    1', 'Mayank Agarwal', 'INDIA', '583'], ['33', '    7', 'Jos Buttler', 'ENGLAND', '582'], ['34', '    1', 'Faf du Plessis', 'SOUTH AFRICA', '570'], ['35', '    1', 'Asad Shafiq', 'PAKISTAN', '567'], ['36', '    9', 'Jermaine Blackwood', 'WEST INDIES', '567'], ['37', '    38', 'KL Rahul', 'INDIA', '559'], ['38', '    2', 'Ravindra Jadeja', 'INDIA', '557'], ['39', '    1', 'Tim Paine', 'AUSTRALIA', '555'], ['40', '    3', 'Abid Ali', 'PAKISTAN', '553'], ['41', '    2', 'Shakib Al Hasan', 'BANGLADESH', '553'], ['42', '    1', 'Colin de Grandhomme', 'NEW ZEALAND', '549'], ['43', '    7', 'Jason Holder', 'WEST INDIES', '548'], ['44', '    2', 'Devon Conway', 'NEW ZEALAND', '547'], ['45', '    19', 'Kraigg Brathwaite', 'WEST INDIES', '545'], ['46', '    3', 'Rassie van der Dussen', 'SOUTH AFRICA', '542'], ['47', '    3', 'Mahmudullah', 'BANGLADESH', '540'], ['48', '    6', 'Faheem Ashraf', 'PAKISTAN', '529'], ['49', '    3', 'Dinesh Chandimal', 'SRI LANKA', '526'], ['50', '    3', 'Sikandar Raza', 'ZIMBABWE', '523'], ['51', '    3', 'Craig Ervine', 'ZIMBABWE', '522'], ['52', '    3', 'Tom Blundell', 'NEW ZEALAND', '519'], ['53', '    2', 'Temba Bavuma', 'SOUTH AFRICA', '518'], ['54', '    1', 'Kusal Mendis', 'SRI LANKA', '514'], ['55', '    5', 'Fawad Alam', 'PAKISTAN', '512'], ['56', '    1', 'Liton Das', 'BANGLADESH', '509'], ['57', '    5', 'Ollie Pope', 'ENGLAND', '504'], ['58', '    1', 'Matthew Wade', 'AUSTRALIA', '501'], ['59', '    1', 'Shan Masood', 'PAKISTAN', '500'], ['60', '    1', 'Oshada Fernando', 'SRI LANKA', '499'], ['61', '    1', 'Lahiru Thirimanne', 'SRI LANKA', '498'], ['62', '    1', 'Joe Burns', 'AUSTRALIA', '497'], ['63', '    4', 'Asghar Afghan', 'AFGHANISTAN', '487'], ['64', '    4', 'Ibrahim Zadran', 'AFGHANISTAN', '486'], ['65', '    5', 'Kusal Perera', 'SRI LANKA', '485'], ['66', '    9', 'Dominic Sibley', 'ENGLAND', '483'], ['67', '    2', 'Shane Dowrich', 'WEST INDIES', '481'], ['68', '    3', 'Hanuma Vihari', 'INDIA', '480'], ['69', '    3', 'Washington Sundar', 'INDIA', '479'], ['70', '    2', 'Joe Denly', 'ENGLAND', '470'], ['71', '    2', 'Shubman Gill', 'INDIA', '468'], ['72', '    5', 'Jonny Bairstow', 'ENGLAND', '463'], ['73', '    3', 'Roston Chase', 'WEST INDIES', '457'], ['74', '    18', 'Nkrumah Bonner', 'WEST INDIES', '455'], ['75', '    3', 'Zak Crawley', 'ENGLAND', '430'], ['76', '    5', 'Kyle Jamieson', 'NEW ZEALAND', '429'], ['77', '    6', 'Kyle Mayers', 'WEST INDIES', '429'], ['78', '    1', 'Shamarh Brooks', 'WEST INDIES', '428'], ['79', '    3', 'Regis Chakabva', 'ZIMBABWE', '427'], ['80', '    –', 'Shai Hope', 'WEST INDIES', '426'], ['81', '    4', 'Ravichandran Ashwin', 'INDIA', '407'], ['82', '    4', 'Haris Sohail', 'PAKISTAN', '400'], ['83', '    5', 'Hashmatullah Shahidi', 'AFGHANISTAN', '397'], ['84', '    3', 'John Campbell', 'WEST INDIES', '397'], ['85', '    6', 'Sam Curran', 'ENGLAND', '396'], ['86', '    6', 'Darren Bravo', 'WEST INDIES', '384'], ['87', '    7', 'Soumya Sarkar', 'BANGLADESH', '378'], ['88', '    7', 'Rahmat Shah', 'AFGHANISTAN', '377'], ['90', '    7', 'Mitchell Starc', 'AUSTRALIA', '370'], ['91', '    7', 'Cameron Green', 'AUSTRALIA', '368'], ['92', '    7', 'Shadman Islam', 'BANGLADESH', '368'], ['93', '    3', 'Chris Woakes', 'ENGLAND', '365'], ['94', '    1', 'Kieran Powell', 'WEST INDIES', '363'], ['95', '    –', 'Mitchell Santner', 'NEW ZEALAND', '355'], ['96', '    –', 'Moeen Ali', 'ENGLAND', '348'], ['97', '    –', 'Daryl Mitchell', 'NEW ZEALAND', '347'], ['98', '    –', 'Joshua Da Silva', 'WEST INDIES', '345'], ['100', '    –', 'Ben Foakes', 'ENGLAND', '336']]
[['1', '    –', 'Babar Azam', 'PAKISTAN', '873'], ['2', '    –', 'Virat Kohli', 'INDIA', '844'], ['3', '    –', 'Rohit Sharma', 'INDIA', '813'], ['4', '    –', 'Ross Taylor', 'NEW ZEALAND', '801'], ['5', '    –', 'Aaron Finch', 'AUSTRALIA', '779'], ['6', '    –', 'Jonny Bairstow', 'ENGLAND', '775'], ['7', '    –', 'David Warner', 'AUSTRALIA', '762'], ['8', '    2', 'Quinton de Kock', 'SOUTH AFRICA', '758'], ['9', '    1', 'Shai Hope', 'WEST INDIES', '758'], ['10', '    1', 'Kane Williamson', 'NEW ZEALAND', '754'], ['11', '    1', 'Fakhar Zaman', 'PAKISTAN', '741'], ['12', '    1', 'Joe Root', 'ENGLAND', '740'], ['13', '    1', 'Mushfiqur Rahim', 'BANGLADESH', '723'], ['14', '    1', 'Imam-ul-Haq', 'PAKISTAN', '717'], ['15', '    3', 'Martin Guptill', 'NEW ZEALAND', '707'], ['16', '    –', 'Shikhar Dhawan', 'INDIA', '704'], ['17', '    –', 'Steven Smith', 'AUSTRALIA', '696'], ['18', '    1', 'Jason Roy', 'ENGLAND', '687'], ['19', '    2', 'Rassie van der Dussen', 'SOUTH AFRICA', '678'], ['20', '    –', 'Glenn Maxwell', 'AUSTRALIA', '674'], ['21', '    2', 'Tamim Iqbal', 'BANGLADESH', '670'], ['22', '    5', 'Alex Carey', 'AUSTRALIA', '669'], ['23', '    1', 'Paul Stirling', 'IRELAND', '664'], ['24', '    1', 'Ben Stokes', 'ENGLAND', '651'], ['25', '    1', 'Eoin Morgan', 'ENGLAND', '650'], ['26', '    2', 'Shakib Al Hasan', 'BANGLADESH', '641'], ['27', '    2', 'KL Rahul', 'INDIA', '636'], ['28', '    3', 'David Miller', 'SOUTH AFRICA', '632'], ['29', '    3', 'Tom Latham', 'NEW ZEALAND', '624'], ['30', '    3', 'Nicholas Pooran', 'WEST INDIES', '615'], ['31', '    3', 'Jos Buttler', 'ENGLAND', '608'], ['32', '    2', 'Shimron Hetmyer', 'WEST INDIES', '607'], ['33', '    2', 'Haris Sohail', 'PAKISTAN', '594'], ['34', '    2', 'Henry Nicholls', 'NEW ZEALAND', '581'], ['35', '    2', 'Aqib Ilyas', 'OMAN', '578'], ['36', '    2', 'Andrew Balbirnie', 'IRELAND', '575'], ['37', '    2', 'Kyle Coetzer', 'SCOTLAND', '573'], ['38', '    2', 'Brendan Taylor', 'ZIMBABWE', '572'], ['39', '    2', 'Mahmudullah', 'BANGLADESH', '571'], ['40', '    2', 'Kusal Perera', 'SRI LANKA', '560'], ['41', '    3', 'Rahmat Shah', 'AFGHANISTAN', '559'], ['42', '    1', 'Evin Lewis', 'WEST INDIES', '558'], ['43', '    2', 'Liton Das', 'BANGLADESH', '558'], ['44', '    4', 'Sean Williams', 'ZIMBABWE', '553'], ['45', '    1', 'Kedar Jadhav', 'INDIA', '552'], ['46', '    1', 'Angelo Mathews', 'SRI LANKA', '550'], ['47', '    2', 'Hardik Pandya', 'INDIA', '548'], ['48', '    3', 'Sikandar Raza', 'ZIMBABWE', '540'], ['49', '    1', 'Danushka Gunathilaka', 'SRI LANKA', '538'], ['50', '    3', 'Kusal Mendis', 'SRI LANKA', '526'], ['51', '    4', 'Imad Wasim', 'PAKISTAN', '525'], ['52', '    16', 'Avishka Fernando', 'SRI LANKA', '522'], ['53', '    3', 'Soumya Sarkar', 'BANGLADESH', '521'], ['54', '    –', 'Marcus Stoinis', 'AUSTRALIA', '517'], ['55', '    3', 'Calum MacLeod', 'SCOTLAND', '508'], ['56', '    3', 'Colin de Grandhomme', 'NEW ZEALAND', '507'], ['57', '    3', 'Najibullah Zadran', 'AFGHANISTAN', '506'], ['58', '    5', 'Sarfaraz Ahmed', 'PAKISTAN', '504'], ['59', '    3', 'Niroshan Dickwella', 'SRI LANKA', '503'], ['60', '    5', 'Hashmatullah Shahidi', 'AFGHANISTAN', '498'], ['61', '    –', 'Marnus Labuschagne', 'AUSTRALIA', '498'], ['62', '    4', 'James Neesham', 'NEW ZEALAND', '495'], ['63', '    6', 'Mohammad Nabi', 'AFGHANISTAN', '494'], ['64', '    6', 'Mitchell Marsh', 'AUSTRALIA', '489'], ['65', '    6', 'Janneman Malan', 'SOUTH AFRICA', '485'], ['66', '    7', 'Asghar Afghan', 'AFGHANISTAN', '479'], ['67', '    7', 'Richie Berrington', 'SCOTLAND', '479'], ['68', '    7', 'Shreyas Iyer', 'INDIA', '472'], ['69', '    8', 'Mohammad Usman', 'UNITED ARAB EMIRATES', '471'], ['70', '    8', 'William Porterfield', 'IRELAND', '471'], ['71', '    5', 'Dhananjaya de Silva', 'SRI LANKA', '461'], ['72', '    8', 'Mitchell Santner', 'NEW ZEALAND', '460'], ['73', '    8', 'Craig Ervine', 'ZIMBABWE', '457'], ['74', '    9', 'Jason Holder', 'WEST INDIES', '446'], ['75', '    7', 'Aiden Markram', 'SOUTH AFRICA', '445'], ['76', '    9', 'Temba Bavuma', 'SOUTH AFRICA', '443'], ['77', '    9', 'Heinrich Klaasen', 'SOUTH AFRICA', '442'], ['78', '    9', 'Andile Phehlukwayo', 'SOUTH AFRICA', '439'], ['79', '    5', 'Assad Vala', 'PAPUA NEW GUINEA', '439'], ['80', '    8', 'Lahiru Thirimanne', 'SRI LANKA', '436'], ['81', '    9', 'Harry Tector', 'IRELAND', '434'], ['82', '    7', 'Ravindra Jadeja', 'INDIA', '434'], ['83', '    8', 'Mohammad Mithun', 'BANGLADESH', '433'], ['84', '    8', 'Rashid Khan', 'AFGHANISTAN', '432'], ['85', '    8', 'George Munsey', 'SCOTLAND', '430'], ['86', '    9', 'Rishabh Pant', 'INDIA', '426'], ['87', '    –', 'Matthew Wade', 'AUSTRALIA', '424'], ['88', '    8', 'Rovman Powell', 'WEST INDIES', '419'], ['89', '    10', 'Curtis Campher', 'IRELAND', '418'], ['90', '    7', 'Dasun Shanaka', 'SRI LANKA', '418'], ['91', '    7', 'Dinesh Chandimal', 'SRI LANKA', '417'], ['92', '    –', 'Kieron Pollard', 'WEST INDIES', '416'], ['93', '    –', 'Gulbadin Naib', 'AFGHANISTAN', '415'], ['94', '    –', 'Mohammad Rizwan', 'PAKISTAN', '414'], ['95', '    5', 'Tony Ura', 'PAPUA NEW GUINEA', '412'], ['96', '    –', 'Moeen Ali', 'ENGLAND', '404'], ['97', '    –', 'Wanindu Hasaranga', 'SRI LANKA', '403'], ['98', '    –', 'Chris Woakes', 'ENGLAND', '403'], ['99', '    –', 'Simi Singh', 'IRELAND', '402'], ['100', '    –', 'Matthew Cross', 'SCOTLAND', '398']]

[['1', '    –', 'Dawid Malan', 'ENGLAND', '841'], ['2', '    –', 'Babar Azam', 'PAKISTAN', '819'], ['3', '    1', 'Devon Conway', 'NEW ZEALAND', '774'], ['4', '    1', 'Aaron Finch', 'AUSTRALIA', '733'], ['5', '    –', 'Virat Kohli', 'INDIA', '717'], ['6', '    –', 'KL Rahul', 'INDIA', '699'], ['7', '    –', 'Mohammad Rizwan', 'PAKISTAN', '692'], ['8', '    1', 'Martin Guptill', 'NEW ZEALAND', '688'], ['9', '    1', 'Evin Lewis', 'WEST INDIES', '664'], ['10', '    –', 'Rassie van der Dussen', 'SOUTH AFRICA', '650'], ['11', '    –', 'Hazratullah Zazai', 'AFGHANISTAN', '636'], ['12', '    1', 'Quinton de Kock', 'SOUTH AFRICA', '609'], ['13', '    3', 'Eoin Morgan', 'ENGLAND', '599'], ['14', '    3', 'Jason Roy', 'ENGLAND', '592'], ['15', '    3', 'Colin Munro', 'NEW ZEALAND', '592'], ['16', '    3', 'Jos Buttler', 'ENGLAND', '590'], ['17', '    3', 'Jonny Bairstow', 'ENGLAND', '588'], ['18', '    3', 'George Munsey', 'SCOTLAND', '583'], ['19', '    5', 'Rohit Sharma', 'INDIA', '577'], ['20', '    2', 'Rahmanullah Gurbaz', 'AFGHANISTAN', '576'], ['21', '    16', 'Mitchell Marsh', 'AUSTRALIA', '575'], ['22', '    1', 'Tim Seifert', 'NEW ZEALAND', '573'], ['23', '    11', 'Glenn Maxwell', 'AUSTRALIA', '567'], ['24', '    –', 'Paul Stirling', 'IRELAND', '566'], ['25', '    10', 'Aiden Markram', 'SOUTH AFRICA', '563'], ['26', '    –', 'Glenn Phillips', 'NEW ZEALAND', '544'], ['28', '    –', 'Richie Berrington', 'SCOTLAND', '542'], ['29', '    –', 'Mohammad Naim', 'BANGLADESH', '536'], ['30', '    2', 'Reeza Hendricks', 'SOUTH AFRICA', '526'], ['31', '    3', 'Shikhar Dhawan', 'INDIA', '526'], ['32', '    1', 'Mohammad Nabi', 'AFGHANISTAN', '523'], ['33', '    9', 'David Miller', 'SOUTH AFRICA', '518'], ['34', '    1', 'Mahmudullah', 'BANGLADESH', '518'], ['35', '    10', 'Shreyas Iyer', 'INDIA', '516'], ['36', '    1', 'Kane Williamson', 'NEW ZEALAND', '512'], ['37', '    1', 'Kyle Coetzer', 'SCOTLAND', '511'], ['38', '    –', 'Andrew Balbirnie', 'IRELAND', '505'], ['39', '    1', 'Tony Ura', 'PAPUA NEW GUINEA', '503'], ['40', '    5', 'Ben Cooper', 'NETHERLANDS', '493'], ['41', '    5', 'Najibullah Zadran', 'AFGHANISTAN', '492'], ['42', '    5', 'Max ODowd', 'NETHERLANDS', '491'], ['43', '    2', 'Kevin O Brien', 'IRELAND', '491'], ['44', '    1', 'Soumya Sarkar', 'BANGLADESH', '483'], ['45', '    3', 'Calum MacLeod', 'SCOTLAND', '483'], ['46', '    3', 'Jatinder Singh', 'OMAN', '482'], ['47', '    3', 'Fakhar Zaman', 'PAKISTAN', '481'], ['48', '    16', 'Nicholas Pooran', 'WEST INDIES', '481'], ['49', '    10', 'Kusal Perera', 'SRI LANKA', '478'], ['50', '    17', 'Suryakumar Yadav', 'INDIA', '477'], ['51', '    1', 'Matthew Cross', 'SCOTLAND', '474'], ['52', '    –', 'Asghar Afghan', 'AFGHANISTAN', '472'], ['53', '    9', 'Shakib Al Hasan', 'BANGLADESH', '469'], ['54', '    –', 'Mohammad Usman', 'UNITED ARAB EMIRATES', '458'], ['55', '    –', 'Tim David', 'SINGAPORE', '457'], ['56', '    26', 'Liton Das', 'BANGLADESH', '449'], ['57', '    4', 'Mohammad Hafeez', 'PAKISTAN', '446'], ['58', '    1', 'Kamran Khan', 'QATAR', '445'], ['59', '    8', 'Lendl Simmons', 'WEST INDIES', '443'], ['60', '    1', 'Kushal Bhurtel', 'NEPAL', '442'], ['61', '    2', 'Ravija Sandaruwan', 'KUWAIT', '435'], ['62', '    4', 'Collins Obuya', 'KENYA', '429'], ['63', '    7', 'Danushka Gunathilaka', 'SRI LANKA', '423'], ['64', '    6', 'Gerhard Erasmus', 'NAMIBIA', '421'], ['66', '    1', 'Faf du Plessis', 'SOUTH AFRICA', '417'], ['67', '    1', 'Kieron Pollard', 'WEST INDIES', '417'], ['68', '    24', 'Temba Bavuma', 'SOUTH AFRICA', '411'], ['69', '    6', 'Nizakat Khan', 'HONG KONG', '405'], ['70', '    13', 'D Arcy Short', 'AUSTRALIA', '404'], ['71', '    11', 'David Warner', 'AUSTRALIA', '401'], ['72', '    –', 'Shimron Hetmyer', 'WEST INDIES', '401'], ['73', '    6', 'Zeeshan Maqsood', 'OMAN', '398'], ['74', '    3', 'Sean Williams', 'ZIMBABWE', '396'], ['75', '    6', 'Rakep Patel', 'KENYA', '394'], ['76', '    2', 'Heinrich Klaasen', 'SOUTH AFRICA', '393'], ['77', '    –', 'Gareth Delany', 'IRELAND', '388'], ['78', '    6', 'Ross Taylor', 'NEW ZEALAND', '388'], ['79', '    6', 'Finn Allen', 'NEW ZEALAND', '384'], ['80', '    6', 'Rishabh Pant', 'INDIA', '383'], ['81', '    5', 'Muhammad Tanveer', 'QATAR', '382'], ['82', '    24', 'Tamim Iqbal', 'BANGLADESH', '381'], ['83', '    10', 'Matthew Wade', 'AUSTRALIA', '378'], ['84', '    4', 'Navneet Dhaliwal', 'CANADA', '375'], ['85', '    5', 'Kusal Mendis', 'SRI LANKA', '373'], ['86', '    3', 'Rohan Mustafa', 'UNITED ARAB EMIRATES', '370'], ['87', '    3', 'Usman Ghani', 'AFGHANISTAN', '367'], ['88', '    –', 'Ryan Burl', 'ZIMBABWE', '366'], ['89', '    6', 'Harry Tector', 'IRELAND', '365'], ['90', '    1', 'Paras Khadka', 'NEPAL', '362'], ['91', '    2', 'Khawar Ali', 'OMAN', '360'], ['92', '    23', 'Mushfiqur Rahim', 'BANGLADESH', '359'], ['93', '    1', 'Ryan ten Doeschate', 'NETHERLANDS', '358'], ['94', '    1', 'Gyanendra Malla', 'NEPAL', '357'], ['95', '    1', 'Nitish Kumar', 'CANADA', '356'], ['96', '    9', 'Manish Pandey', 'INDIA', '354'], ['97', '    15', 'Steven Smith', 'AUSTRALIA', '352'], ['99', '    23', 'Sabbir Rahman', 'BANGLADESH', '345'], ['100', '    1', 'Samiullah Shinwari', 'AFGHANISTAN', '344']]
[['1', '    –', 'Pat Cummins', 'AUSTRALIA', '908'], ['2', '    –', 'Ravichandran Ashwin', 'INDIA', '848'], ['3', '    –', 'Tim Southee', 'NEW ZEALAND', '824'], ['4', '    –', 'Josh Hazlewood', 'AUSTRALIA', '816'], ['5', '    –', 'Neil Wagner', 'NEW ZEALAND', '810'], ['6', '    2', 'James Anderson', 'ENGLAND', '800'], ['7', '    1', 'Kagiso Rabada', 'SOUTH AFRICA', '798'], ['8', '    1', 'Stuart Broad', 'ENGLAND', '764'], ['9', '    1', 'Jason Holder', 'WEST INDIES', '756'], ['10', '    9', 'Jasprit Bumrah', 'INDIA', '754'], ['11', '    1', 'Kemar Roach', 'WEST INDIES', '751'], ['12', '    3', 'Mitchell Starc', 'AUSTRALIA', '744'], ['13', '    2', 'Trent Boult', 'NEW ZEALAND', '738'], ['14', '    1', 'Kyle Jamieson', 'NEW ZEALAND', '725'], ['15', '    1', 'Hasan Ali', 'PAKISTAN', '723'], ['16', '    –', 'Ishant Sharma', 'INDIA', '717'], ['17', '    2', 'Mohammad Abbas', 'PAKISTAN', '709'], ['18', '    4', 'Shaheen Afridi', 'PAKISTAN', '699'], ['19', '    1', 'Mohammed Shami', 'INDIA', '676'], ['20', '    –', 'Nathan Lyon', 'AUSTRALIA', '668'], ['21', '    4', 'Ravindra Jadeja', 'INDIA', '645'], ['22', '    1', 'Suranga Lakmal', 'SRI LANKA', '635'], ['23', '    1', 'Mehidy Hasan', 'BANGLADESH', '610'], ['24', '    2', 'Shakib Al Hasan', 'BANGLADESH', '605'], ['25', '    2', 'Taijul Islam', 'BANGLADESH', '605'], ['26', '    3', 'Chris Woakes', 'ENGLAND', '602'], ['27', '    2', 'Shannon Gabriel', 'WEST INDIES', '600'], ['28', '    –', 'Keshav Maharaj', 'SOUTH AFRICA', '593'], ['29', '    1', 'Umesh Yadav', 'INDIA', '579'], ['30', '    1', 'Yasir Shah', 'PAKISTAN', '573'], ['31', '    –', 'Anrich Nortje', 'SOUTH AFRICA', '564'], ['32', '    3', 'Rashid Khan', 'AFGHANISTAN', '543'], ['33', '    1', 'Jack Leach', 'ENGLAND', '543'], ['34', '    –', 'Axar Patel', 'INDIA', '536'], ['35', '    2', 'Ben Stokes', 'ENGLAND', '536'], ['36', '    –', 'Moeen Ali', 'ENGLAND', '495'], ['37', '    5', 'Mark Wood', 'ENGLAND', '477'], ['38', '    14', 'Mohammed Siraj', 'INDIA', '465'], ['39', '    2', 'Dilruwan Perera', 'SRI LANKA', '459'], ['40', '    2', 'Lahiru Kumara', 'SRI LANKA', '459'], ['41', '    2', 'Lasith Embuldeniya', 'SRI LANKA', '444'], ['42', '    2', 'Lungi Ngidi', 'SOUTH AFRICA', '436'], ['43', '    –', 'Colin de Grandhomme', 'NEW ZEALAND', '424'], ['44', '    3', 'Roston Chase', 'WEST INDIES', '423'], ['46', '    1', 'Blessing Muzarabani', 'ZIMBABWE', '391'], ['47', '    2', 'Vishwa Fernando', 'SRI LANKA', '388'], ['48', '    2', 'Nauman Ali', 'PAKISTAN', '387'], ['49', '    4', 'Jofra Archer', 'ENGLAND', '383'], ['50', '    2', 'Dominic Bess', 'ENGLAND', '381'], ['51', '    –', 'Praveen Jayawickrama', 'SRI LANKA', '380'], ['52', '    1', 'Kyle Mayers', 'WEST INDIES', '374'], ['53', '    1', 'Nayeem Hasan', 'BANGLADESH', '366'], ['54', '    1', 'Amir Hamza', 'AFGHANISTAN', '364'], ['55', '    25', 'Shardul Thakur', 'INDIA', '357'], ['56', '    6', 'Sam Curran', 'ENGLAND', '350'], ['57', '    1', 'Kuldeep Yadav', 'INDIA', '348'], ['59', '    1', 'Wiaan Mulder', 'SOUTH AFRICA', '333'], ['60', '    3', 'Rahkeem Cornwall', 'WEST INDIES', '331'], ['61', '    1', 'Jubair Hossain', 'BANGLADESH', '326'], ['62', '    1', 'Abu Jayed', 'BANGLADESH', '323'], ['63', '    1', 'Ajaz Patel', 'NEW ZEALAND', '320'], ['64', '    1', 'Sikandar Raza', 'ZIMBABWE', '315'], ['65', '    1', 'Matt Henry', 'NEW ZEALAND', '304'], ['66', '    1', 'Alzarri Joseph', 'WEST INDIES', '299'], ['67', '    2', 'Olly Stone', 'ENGLAND', '289'], ['68', '    3', 'Kasun Rajitha', 'SRI LANKA', '288'], ['69', '    1', 'Jomel Warrican', 'WEST INDIES', '281'], ['70', '    2', 'Mustafizur Rahman', 'BANGLADESH', '276'], ['71', '    10', 'Faheem Ashraf', 'PAKISTAN', '271'], ['72', '    3', 'Yamin Ahmadzai', 'AFGHANISTAN', '260'], ['73', '    3', 'Dushmantha Chameera', 'SRI LANKA', '248'], ['74', '    3', 'Donald Tiripano', 'ZIMBABWE', '248'], ['75', '    3', 'Victor Nyauchi', 'ZIMBABWE', '247'], ['76', '    3', 'Naseem Shah', 'PAKISTAN', '244'], ['77', '    5', 'Mitchell Santner', 'NEW ZEALAND', '237'], ['78', '    5', 'Haris Sohail', 'PAKISTAN', '225'], ['79', '    6', 'George Linde', 'SOUTH AFRICA', '222'], ['80', '    8', 'Dasun Shanaka', 'SRI LANKA', '210'], ['81', '    8', 'Taskin Ahmed', 'BANGLADESH', '206'], ['82', '    8', 'Mahmudullah', 'BANGLADESH', '205'], ['83', '    3', 'Joe Root', 'ENGLAND', '202'], ['84', '    7', 'Ramesh Mendis', 'SRI LANKA', '197'], ['85', '    7', 'Shadab Khan', 'PAKISTAN', '185'], ['86', '    7', 'Sean Williams', 'ZIMBABWE', '181'], ['87', '    8', 'Shahbaz Nadeem', 'INDIA', '168'], ['88', '    8', 'Dhananjaya de Silva', 'SRI LANKA', '161'], ['89', '    10', 'Kraigg Brathwaite', 'WEST INDIES', '133'], ['90', '    10', 'Ryan Burl', 'ZIMBABWE', '132'], ['91', '    –', 'Zahir Khan', 'AFGHANISTAN', '128'], ['92', '    –', 'Angelo Mathews', 'SRI LANKA', '123'], ['93', '    –', 'Rubel Hossain', 'BANGLADESH', '122'], ['94', '    –', 'Marnus Labuschagne', 'AUSTRALIA', '122'], ['95', '    –', 'Kane Williamson', 'NEW ZEALAND', '116'], ['96', '    –', 'Washington Sundar', 'INDIA', '107'], ['97', '    –', 'Dean Elgar', 'SOUTH AFRICA', '102'], ['98', '    –', 'Tendai Chisoro', 'ZIMBABWE', '88'], ['99', '    –', 'Navdeep Saini', 'INDIA', '86']]

[['1', '    –', 'Trent Boult', 'NEW ZEALAND', '737'], ['2', '    5', 'Josh Hazlewood', 'AUSTRALIA', '709'], ['3', '    1', 'Mujeeb Ur Rahman', 'AFGHANISTAN', '708'], ['4', '    1', 'Chris Woakes', 'ENGLAND', '700'], ['5', '    1', 'Mehidy Hasan', 'BANGLADESH', '692'], ['6', '    1', 'Matt Henry', 'NEW ZEALAND', '691'], ['7', '    1', 'Jasprit Bumrah', 'INDIA', '679'], ['8', '    10', 'Mitchell Starc', 'AUSTRALIA', '652'], ['9', '    1', 'Shakib Al Hasan', 'BANGLADESH', '650'], ['10', '    1', 'Kagiso Rabada', 'SOUTH AFRICA', '648'], ['11', '    –', 'Mustafizur Rahman', 'BANGLADESH', '640'], ['12', '    2', 'Pat Cummins', 'AUSTRALIA', '636'], ['13', '    1', 'Shaheen Afridi', 'PAKISTAN', '630'], ['14', '    1', 'Mohammad Amir', 'PAKISTAN', '628'], ['15', '    1', 'Rashid Khan', 'AFGHANISTAN', '626'], ['16', '    –', 'Adam Zampa', 'AUSTRALIA', '625'], ['17', '    2', 'Bhuvneshwar Kumar', 'INDIA', '621'], ['18', '    1', 'Lockie Ferguson', 'NEW ZEALAND', '619'], ['19', '    –', 'Jofra Archer', 'ENGLAND', '609'], ['20', '    5', 'Akila Dananjaya', 'SRI LANKA', '604'], ['21', '    1', 'Yuzvendra Chahal', 'INDIA', '603'], ['22', '    1', 'Lungi Ngidi', 'SOUTH AFRICA', '599'], ['23', '    1', 'Mohammad Nabi', 'AFGHANISTAN', '596'], ['24', '    1', 'Mark Wood', 'ENGLAND', '594'], ['25', '    2', 'Alzarri Joseph', 'WEST INDIES', '592'], ['26', '    2', 'Mitchell Santner', 'NEW ZEALAND', '583'], ['27', '    1', 'Mohammed Shami', 'INDIA', '566'], ['28', '    –', 'Kuldeep Yadav', 'INDIA', '562'], ['29', '    1', 'Ravindra Jadeja', 'INDIA', '550'], ['30', '    1', 'Sheldon Cottrell', 'WEST INDIES', '541'], ['31', '    –', 'Ahmed Raza', 'UNITED ARAB EMIRATES', '531'], ['32', '    1', 'Andy McBrine', 'IRELAND', '527'], ['33', '    1', 'Shadab Khan', 'PAKISTAN', '517'], ['34', '    1', 'Dushmantha Chameera', 'SRI LANKA', '514'], ['35', '    1', 'Wanindu Hasaranga', 'SRI LANKA', '508'], ['36', '    2', 'Colin de Grandhomme', 'NEW ZEALAND', '508'], ['37', '    2', 'Tabraiz Shamsi', 'SOUTH AFRICA', '501'], ['38', '    2', 'David Willey', 'ENGLAND', '501'], ['39', '    2', 'Tim Southee', 'NEW ZEALAND', '500'], ['40', '    2', 'Andile Phehlukwayo', 'SOUTH AFRICA', '497'], ['41', '    2', 'Adil Rashid', 'ENGLAND', '497'], ['42', '    2', 'Ish Sodhi', 'NEW ZEALAND', '496'], ['43', '    2', 'Mark Watt', 'SCOTLAND', '490'], ['44', '    3', 'Imad Wasim', 'PAKISTAN', '488'], ['45', '    3', 'Hasan Ali', 'PAKISTAN', '483'], ['46', '    3', 'Usman Shinwari', 'PAKISTAN', '482'], ['47', '    1', 'Jhye Richardson', 'AUSTRALIA', '480'], ['48', '    2', 'Rohan Mustafa', 'UNITED ARAB EMIRATES', '477'], ['49', '    2', 'Simi Singh', 'IRELAND', '473'], ['50', '    3', 'Mashrafe Mortaza', 'BANGLADESH', '469'], ['51', '    3', 'Mohammad Saifuddin', 'BANGLADESH', '468'], ['52', '    3', 'Safyaan Sharif', 'SCOTLAND', '467'], ['53', '    3', 'Tendai Chatara', 'ZIMBABWE', '465'], ['54', '    4', 'Nuwan Pradeep', 'SRI LANKA', '459'], ['55', '    5', 'James Neesham', 'NEW ZEALAND', '458'], ['57', '    –', 'Jason Holder', 'WEST INDIES', '451'], ['58', '    6', 'Moeen Ali', 'ENGLAND', '449'], ['59', '    6', 'Wahab Riaz', 'PAKISTAN', '447'], ['60', '    6', 'Faheem Ashraf', 'PAKISTAN', '445'], ['62', '    5', 'Suranga Lakmal', 'SRI LANKA', '443'], ['63', '    6', 'Sikandar Raza', 'ZIMBABWE', '440'], ['64', '    6', 'Blessing Muzarabani', 'ZIMBABWE', '437'], ['65', '    6', 'Tom Curran', 'ENGLAND', '436'], ['66', '    32', 'Ashton Agar', 'AUSTRALIA', '436'], ['67', '    5', 'Taskin Ahmed', 'BANGLADESH', '434'], ['68', '    5', 'Anrich Nortje', 'SOUTH AFRICA', '431'], ['69', '    7', 'Josh Davey', 'SCOTLAND', '427'], ['71', '    9', 'Craig Young', 'IRELAND', '421'], ['72', '    9', 'Sean Williams', 'ZIMBABWE', '420'], ['73', '    4', 'Kane Richardson', 'AUSTRALIA', '416'], ['74', '    10', 'Ben Stokes', 'ENGLAND', '410'], ['75', '    10', 'Shardul Thakur', 'INDIA', '405'], ['76', '    11', 'Rubel Hossain', 'BANGLADESH', '400'], ['77', '    12', 'Gulbadin Naib', 'AFGHANISTAN', '399'], ['78', '    8', 'Hardik Pandya', 'INDIA', '394'], ['79', '    12', 'Alasdair Evans', 'SCOTLAND', '394'], ['80', '    12', 'Keshav Maharaj', 'SOUTH AFRICA', '394'], ['81', '    12', 'Barry McCarthy', 'IRELAND', '391'], ['82', '    8', 'Mitchell Marsh', 'AUSTRALIA', '390'], ['83', '    5', 'Dhananjaya de Silva', 'SRI LANKA', '388'], ['84', '    12', 'Marcus Stoinis', 'AUSTRALIA', '377'], ['85', '    12', 'Lakshan Sandakan', 'SRI LANKA', '376'], ['86', '    13', 'Taijul Islam', 'BANGLADESH', '374'], ['87', '    13', 'Mohammad Nawaz', 'PAKISTAN', '370'], ['88', '    –', 'Donald Tiripano', 'ZIMBABWE', '367'], ['89', '    –', 'Assad Vala', 'PAPUA NEW GUINEA', '361'], ['90', '    –', 'Fred Klaassen', 'NETHERLANDS', '358'], ['91', '    –', 'George Dockrell', 'IRELAND', '357'], ['92', '    –', 'Oshane Thomas', 'WEST INDIES', '355'], ['93', '    –', 'Kyle Jamieson', 'NEW ZEALAND', '352'], ['94', '    –', 'Michael Leask', 'SCOTLAND', '351'], ['95', '    –', 'Zeeshan Maqsood', 'OMAN', '350'], ['96', '    –', 'Sharafuddin Ashraf', 'AFGHANISTAN', '347'], ['97', '    –', 'Roston Chase', 'WEST INDIES', '347'], ['98', '    –', 'Bilal Khan', 'OMAN', '344'], ['99', '    –', 'Saurabh Netravalkar', 'UNITED STATES', '343'], ['100', '    –', 'Norman Vanua', 'PAPUA NEW GUINEA', '342']]
[['1', '    –', 'Tabraiz Shamsi', 'SOUTH AFRICA', '792'], ['2', '    1', 'Wanindu Hasaranga', 'SRI LANKA', '764'], ['3', '    1', 'Rashid Khan', 'AFGHANISTAN', '719'], ['4', '    –', 'Adil Rashid', 'ENGLAND', '689'], ['5', '    –', 'Mujeeb Ur Rahman', 'AFGHANISTAN', '687'], ['6', '    –', 'Tim Southee', 'NEW ZEALAND', '669'], ['7', '    1', 'Ashton Agar', 'AUSTRALIA', '649'], ['8', '    1', 'Adam Zampa', 'AUSTRALIA', '648'], ['9', '    –', 'Ish Sodhi', 'NEW ZEALAND', '640'], ['10', '    30', 'Mustafizur Rahman', 'BANGLADESH', '619'], ['11', '    –', 'Mitchell Santner', 'NEW ZEALAND', '616'], ['12', '    10', 'Shakib Al Hasan', 'BANGLADESH', '610'], ['13', '    2', 'Mark Watt', 'SCOTLAND', '595'], ['14', '    6', 'Bhuvneshwar Kumar', 'INDIA', '594'], ['15', '    2', 'Chris Jordan', 'ENGLAND', '579'], ['16', '    4', 'Lakshan Sandakan', 'SRI LANKA', '574'], ['17', '    7', 'Fabian Allen', 'WEST INDIES', '572'], ['18', '    –', 'Mark Wood', 'ENGLAND', '563'], ['19', '    5', 'Washington Sundar', 'INDIA', '562'], ['20', '    22', 'Dushmantha Chameera', 'SRI LANKA', '555'], ['21', '    –', 'Mohammad Nabi', 'AFGHANISTAN', '546'], ['22', '    6', 'Sheldon Cottrell', 'WEST INDIES', '546'], ['23', '    10', 'Shaheen Afridi', 'PAKISTAN', '543'], ['24', '    7', 'Yuzvendra Chahal', 'INDIA', '529'], ['25', '    1', 'Alasdair Evans', 'SCOTLAND', '529'], ['26', '    1', 'Karim Janat', 'AFGHANISTAN', '527'], ['27', '    8', 'George Linde', 'SOUTH AFRICA', '524'], ['28', '    41', 'Blessing Muzarabani', 'ZIMBABWE', '522'], ['29', '    –', 'Bilal Khan', 'OMAN', '521'], ['30', '    2', 'Lockie Ferguson', 'NEW ZEALAND', '515'], ['31', '    8', 'Shardul Thakur', 'INDIA', '508'], ['33', '    8', 'Jasprit Bumrah', 'INDIA', '504'], ['34', '    –', 'Josh Hazlewood', 'AUSTRALIA', '502'], ['35', '    16', 'Kane Richardson', 'AUSTRALIA', '501'], ['36', '    19', 'Akila Dananjaya', 'SRI LANKA', '501'], ['37', '    13', 'Faheem Ashraf', 'PAKISTAN', '498'], ['38', '    1', 'Deepak Chahar', 'INDIA', '497'], ['39', '    1', 'Jofra Archer', 'ENGLAND', '495'], ['40', '    4', 'Mark Adair', 'IRELAND', '495'], ['41', '    2', 'Lungi Ngidi', 'SOUTH AFRICA', '487'], ['42', '    14', 'Imad Wasim', 'PAKISTAN', '484'], ['43', '    41', 'Mohammad Saifuddin', 'BANGLADESH', '479'], ['44', '    7', 'Shadab Khan', 'PAKISTAN', '478'], ['45', '    3', 'Trent Boult', 'NEW ZEALAND', '473'], ['46', '    13', 'Mitchell Starc', 'AUSTRALIA', '472'], ['47', '    2', 'Tom Curran', 'ENGLAND', '468'], ['48', '    2', 'David Willey', 'ENGLAND', '468'], ['49', '    19', 'Haris Rauf', 'PAKISTAN', '467'], ['50', '    4', 'Dwayne Bravo', 'WEST INDIES', '467'], ['51', '    –', 'Safyaan Sharif', 'SCOTLAND', '466'], ['52', '    –', 'Ahmed Raza', 'UNITED ARAB EMIRATES', '463'], ['53', '    –', 'Roelof van der Merwe', 'NETHERLANDS', '463'], ['54', '    –', 'Sam Curran', 'ENGLAND', '462'], ['55', '    15', 'Jason Holder', 'WEST INDIES', '456'], ['56', '    1', 'Paul van Meekeren', 'NETHERLANDS', '454'], ['57', '    18', 'Beuran Hendricks', 'SOUTH AFRICA', '453'], ['58', '    –', 'Bernard Scholtz', 'NAMIBIA', '452'], ['59', '    15', 'Lasith Malinga', 'SRI LANKA', '450'], ['60', '    1', 'Brandon Glover', 'NETHERLANDS', '449'], ['61', '    5', 'Andile Phehlukwayo', 'SOUTH AFRICA', '449'], ['62', '    21', 'Mohammad Hasnain', 'PAKISTAN', '446'], ['63', '    1', 'Hasan Ali', 'PAKISTAN', '446'], ['64', '    3', 'Shem Obado', 'KENYA', '444'], ['65', '    2', 'Khawar Ali', 'OMAN', '442'], ['67', '    22', 'Mohammad Nawaz', 'PAKISTAN', '440'], ['68', '    3', 'Norman Vanua', 'PAPUA NEW GUINEA', '437'], ['70', '    3', 'Pieter Seelaar', 'NETHERLANDS', '436'], ['71', '    6', 'Andrew Tye', 'AUSTRALIA', '428'], ['72', '    1', 'Mohammad Nadeem', 'OMAN', '420'], ['73', '    17', 'Simi Singh', 'IRELAND', '414'], ['74', '    2', 'Rohan Mustafa', 'UNITED ARAB EMIRATES', '412'], ['75', '    –', 'Wellington Masakadza', 'ZIMBABWE', '410'], ['77', '    2', 'Sandeep Lamichhane', 'NEPAL', '405'], ['78', '    2', 'Sultan Ahmed', 'UNITED ARAB EMIRATES', '405'], ['79', '    8', 'Kagiso Rabada', 'SOUTH AFRICA', '404'], ['80', '    20', 'Pat Cummins', 'AUSTRALIA', '403'], ['81', '    1', 'Josh Davey', 'SCOTLAND', '403'], ['82', '    8', 'Kuldeep Yadav', 'INDIA', '399'], ['83', '    –', 'Hardik Pandya', 'INDIA', '393'], ['84', '    4', 'Krunal Pandya', 'INDIA', '390'], ['85', '    7', 'Gareth Delany', 'IRELAND', '389'], ['86', '    1', 'Timm van der Gugten', 'NETHERLANDS', '389'], ['87', '    6', 'Isuru Udana', 'SRI LANKA', '389'], ['88', '    2', 'Zahoor Khan', 'UNITED ARAB EMIRATES', '386'], ['89', '    –', 'Fred Klaassen', 'NETHERLANDS', '383'], ['90', '    1', 'Charles Amini', 'PAPUA NEW GUINEA', '381'], ['91', '    19', 'Billy Stanlake', 'AUSTRALIA', '379'], ['93', '    1', 'Naveen-ul-Haq', 'AFGHANISTAN', '378'], ['94', '    32', 'Al-Amin Hossain', 'BANGLADESH', '378'], ['95', '    1', 'Hamza Tahir', 'SCOTLAND', '373'], ['96', '    28', 'Usman Qadir', 'PAKISTAN', '371'], ['97', '    2', 'Ehsan Khan', 'HONG KONG', '371'], ['98', '    11', 'Anrich Nortje', 'SOUTH AFRICA', '370'], ['99', '    3', 'Nosaina Pokana', 'PAPUA NEW GUINEA', '367'], ['100', '    1', 'Ben Stokes', 'ENGLAND', '362']]

[['1', '    –', 'Jason Holder', 'WEST INDIES', '414'], ['2', '    –', 'Ben Stokes', 'ENGLAND', '362'], ['3', '    –', 'Ravindra Jadeja', 'INDIA', '359'], ['4', '    –', 'Ravichandran Ashwin', 'INDIA', '345'], ['5', '    –', 'Shakib Al Hasan', 'BANGLADESH', '334'], ['6', '    –', 'Kyle Jamieson', 'NEW ZEALAND', '311'], ['7', '    –', 'Mitchell Starc', 'AUSTRALIA', '275'], ['8', '    –', 'Pat Cummins', 'AUSTRALIA', '249'], ['9', '    –', 'Colin de Grandhomme', 'NEW ZEALAND', '232'], ['10', '    –', 'Chris Woakes', 'ENGLAND', '219']]
[['1', '    –', 'Shakib Al Hasan', 'BANGLADESH', '416'], ['2', '    –', 'Mohammad Nabi', 'AFGHANISTAN', '294'], ['3', '    –', 'Chris Woakes', 'ENGLAND', '282'], ['4', '    –', 'Rashid Khan', 'AFGHANISTAN', '270'], ['5', '    –', 'Mitchell Santner', 'NEW ZEALAND', '268'], ['6', '    –', 'Ben Stokes', 'ENGLAND', '266'], ['7', '    –', 'Colin de Grandhomme', 'NEW ZEALAND', '257'], ['8', '    –', 'Imad Wasim', 'PAKISTAN', '256'], ['9', '    –', 'Ravindra Jadeja', 'INDIA', '238'], ['10', '    –', 'Sikandar Raza', 'ZIMBABWE', '237']]
[['1', '    1', 'Shakib Al Hasan', 'BANGLADESH', '286'], ['2', '    1', 'Mohammad Nabi', 'AFGHANISTAN', '285'], ['3', '    –', 'Richie Berrington', 'SCOTLAND', '194'], ['4', '    2', 'Khawar Ali', 'OMAN', '159'], ['5', '    3', 'Collins Obuya', 'KENYA', '153'], ['6', '    3', 'Rohan Mustafa', 'UNITED ARAB EMIRATES', '152'], ['7', '    3', 'Glenn Maxwell', 'AUSTRALIA', '151'], ['8', '    3', 'Gareth Delany', 'IRELAND', '150'], ['9', '    1', 'Mitchell Marsh', 'AUSTRALIA', '141'], ['10', '    3', 'Sean Williams', 'ZIMBABWE', '140']]
[['1', 'NEW ZEALAND', '126', '2764'], ['2', 'INDIA', '119', '2987'], ['3', 'AUSTRALIA', '108', '1844'], ['4', 'ENGLAND', '107', '3753'], ['5', 'PAKISTAN', '94', '2247'], ['6', 'SOUTH AFRICA', '88', '1675'], ['7', 'WEST INDIES', '78', '2114'], ['8', 'SRI LANKA', '78', '2095'], ['9', 'BANGLADESH', '49', '779'], ['10', 'ZIMBABWE', '31', '342']]
[['1', 'NEW ZEALAND', '121', '2054'], ['2', 'ENGLAND', '119', '3793'], ['3', 'AUSTRALIA', '116', '3244'], ['4', 'INDIA', '113', '3624'], ['5', 'SOUTH AFRICA', '103', '2267'], ['6', 'PAKISTAN', '93', '2524'], ['7', 'BANGLADESH', '91', '2639'], ['8', 'WEST INDIES', '84', '2523'], ['9', 'SRI LANKA', '79', '2303'], ['10', 'AFGHANISTAN', '62', '1054'], ['11', 'NETHERLANDS', '48', '336'], ['12', 'IRELAND', '46', '1067'], ['13', 'ZIMBABWE', '38', '646'], ['14', 'SCOTLAND', '37', '258'], ['15', 'OMAN', '34', '240'], ['16', 'NEPAL', '24', '119'], ['17', 'UAE', '21', '190'], ['18', 'NAMIBIA', '16', '97'], ['19', 'UNITED STATES', '12', '93'], ['20', 'PAPUA NEW GUINEA', '0', '0']]
[['1', 'ENGLAND', '278', '7786'], ['2', 'INDIA', '273', '7093'], ['3', 'NEW ZEALAND', '263', '6048'], ['4', 'PAKISTAN', '261', '8883'], ['5', 'SOUTH AFRICA', '246', '6640'], ['6', 'AUSTRALIA', '240', '7923'], ['7', 'AFGHANISTAN', '236', '2826'], ['8', 'SRI LANKA', '235', '4456'], ['9', 'WEST INDIES', '234', '6792'], ['10', 'BANGLADESH', '234', '4915'], ['11', 'ZIMBABWE', '193', '4249'], ['12', 'NEPAL', '187', '3556'], ['13', 'IRELAND', '187', '3921'], ['14', 'SCOTLAND', '185', '2035'], ['15', 'UAE', '184', '2023'], ['16', 'PAPUA NEW GUINEA', '179', '2501'], ['17', 'NETHERLANDS', '175', '3504'], ['18', 'OMAN', '173', '1732'], ['19', 'NAMIBIA', '157', '2204'], ['20', 'SINGAPORE', '140', '1678'], ['21', 'QATAR', '129', '1422'], ['22', 'CANADA', '126', '1263'], ['23', 'HONG KONG', '121', '1572'], ['24', 'JERSEY', '114', '1481'], ['25', 'KENYA', '112', '894'], ['26', 'ITALY', '111', '663'], ['27', 'KUWAIT', '108', '866'], ['28', 'SAUDI ARABIA', '107', '428'], ['29', 'DENMARK', '101', '606'], ['30', 'BERMUDA', '95', '568'], ['31', 'MALAYSIA', '86', '1723'], ['32', 'UGANDA', '85', '847'], ['33', 'GERMANY', '84', '759'], ['34', 'UNITED STATES', '81', '644'], ['35', 'BOTSWANA', '79', '786'], ['36', 'NIGERIA', '75', '375'], ['37', 'GUERNSEY', '72', '645'], ['39', 'AUSTRIA', '65', '650'], ['41', 'SPAIN', '57', '457'], ['42', 'BAHRAIN', '57', '227'], ['43', 'BELGIUM', '56', '502'], ['44', 'TANZANIA', '56', '167'], ['45', 'PHILIPPINES', '48', '241'], ['46', 'MEXICO', '45', '313'], ['48', 'VANUATU', '44', '435'], ['49', 'BELIZE', '42', '209'], ['50', 'ARGENTINA', '41', '206'], ['51', 'PERU', '36', '179'], ['52', 'FIJI', '35', '105'], ['53', 'MALAWI', '35', '312'], ['54', 'PANAMA', '32', '162'], ['55', 'SAMOA', '32', '159'], ['56', 'JAPAN', '32', '126'], ['57', 'COSTA RICA', '32', '126'], ['58', 'MALTA', '31', '214'], ['59', 'LUXEMBOURG', '30', '358'], ['60', 'THAILAND', '25', '175'], ['61', 'BULGARIA', '24', '313'], ['62', 'PORTUGAL', '24', '119'], ['63', 'CZECH REPUBLIC', '22', '356'], ['64', 'FINLAND', '21', '106'], ['65', 'SOUTH KOREA', '20', '78'], ['66', 'MOZAMBIQUE', '19', '175'], ['67', 'ISLE OF MAN', '19', '77'], ['69', 'BHUTAN', '12', '47'], ['70', 'MALDIVES', '9', '65'], ['71', 'SAINT HELENA', '9', '55'], ['72', 'BRAZIL', '8', '39'], ['73', 'CHILE', '4', '19'], ['74', 'GIBRALTAR', '3', '13'], ['75', 'MYANMAR', '0', '1'], ['76', 'INDONESIA', '0', '0'], ['77', 'LESOTHO', '0', '0'], ['78', 'RWANDA', '0', '0'], ['81', 'CHINA', '0', '0']]

In [8]:
testdf = pd.DataFrame(testbatrankings,columns = ["Position","drop","Player","Country","Rating"])
testdf.drop(columns = ["drop"],axis="columns",inplace=True)
testdf

   Position                 Player       Country Rating
0         1        Kane Williamson   NEW ZEALAND    901
1         2               Joe Root       ENGLAND    893
2         3           Steven Smith     AUSTRALIA    891
3         4     Marnus Labuschagne     AUSTRALIA    878
4         5            Virat Kohli         INDIA    776
5         6           Rohit Sharma         INDIA    773
6         7           Rishabh Pant         INDIA    736
7         8             Babar Azam      PAKISTAN    725
8         9           David Warner     AUSTRALIA    724
9        10        Quinton de Kock  SOUTH AFRICA    717
10       11         Henry Nicholls   NEW ZEALAND    714
11       12     Dimuth Karunaratne     SRI LANKA    712
12       13            Ross Taylor   NEW ZEALAND    693
13       14             Tom Latham   NEW ZEALAND    677
14       15         Ajinkya Rahane         INDIA    677
15       16             Ben Stokes       ENGLAND    677
16       17             Dean Elgar  SOUTH AFRICA    661
17       18      Cheteshwar Pujara         INDIA    658
18       19              Azhar Ali      PAKISTAN    658
19       20          Aiden Markram  SOUTH AFRICA    651
20       21        Mohammad Rizwan      PAKISTAN    637
21       22        Mushfiqur Rahim    BANGLADESH    626
22       23            Travis Head     AUSTRALIA    618
23       24         Angelo Mathews     SRI LANKA    618
24       25            Tamim Iqbal    BANGLADESH    605
25       26          Sean Williams      ZIMBABWE    603
26       27         Brendan Taylor      ZIMBABWE    603
27       28             Rory Burns       ENGLAND    600
28       29          Mominul Haque    BANGLADESH    596
29       30     Niroshan Dickwella     SRI LANKA    589
30       31    Dhananjaya de Silva     SRI LANKA    588
31       32         Mayank Agarwal         INDIA    583
32       33            Jos Buttler       ENGLAND    582
33       34         Faf du Plessis  SOUTH AFRICA    570
34       35            Asad Shafiq      PAKISTAN    567
35       36     Jermaine Blackwood   WEST INDIES    567
36       37               KL Rahul         INDIA    559
37       38        Ravindra Jadeja         INDIA    557
38       39              Tim Paine     AUSTRALIA    555
39       40               Abid Ali      PAKISTAN    553
40       41        Shakib Al Hasan    BANGLADESH    553
41       42    Colin de Grandhomme   NEW ZEALAND    549
42       43           Jason Holder   WEST INDIES    548
43       44           Devon Conway   NEW ZEALAND    547
44       45      Kraigg Brathwaite   WEST INDIES    545
45       46  Rassie van der Dussen  SOUTH AFRICA    542
46       47            Mahmudullah    BANGLADESH    540
47       48          Faheem Ashraf      PAKISTAN    529
48       49       Dinesh Chandimal     SRI LANKA    526
49       50          Sikandar Raza      ZIMBABWE    523
50       51           Craig Ervine      ZIMBABWE    522
51       52           Tom Blundell   NEW ZEALAND    519
52       53           Temba Bavuma  SOUTH AFRICA    518
53       54           Kusal Mendis     SRI LANKA    514
54       55             Fawad Alam      PAKISTAN    512
55       56              Liton Das    BANGLADESH    509
56       57             Ollie Pope       ENGLAND    504
57       58           Matthew Wade     AUSTRALIA    501
58       59            Shan Masood      PAKISTAN    500
59       60        Oshada Fernando     SRI LANKA    499
60       61      Lahiru Thirimanne     SRI LANKA    498
61       62              Joe Burns     AUSTRALIA    497
62       63          Asghar Afghan   AFGHANISTAN    487
63       64         Ibrahim Zadran   AFGHANISTAN    486
64       65           Kusal Perera     SRI LANKA    485
65       66         Dominic Sibley       ENGLAND    483
66       67          Shane Dowrich   WEST INDIES    481
67       68          Hanuma Vihari         INDIA    480
68       69      Washington Sundar         INDIA    479
69       70              Joe Denly       ENGLAND    470
70       71           Shubman Gill         INDIA    468
71       72         Jonny Bairstow       ENGLAND    463
72       73           Roston Chase   WEST INDIES    457
73       74         Nkrumah Bonner   WEST INDIES    455
74       75            Zak Crawley       ENGLAND    430
75       76          Kyle Jamieson   NEW ZEALAND    429
76       77            Kyle Mayers   WEST INDIES    429
77       78         Shamarh Brooks   WEST INDIES    428
78       79         Regis Chakabva      ZIMBABWE    427
79       80              Shai Hope   WEST INDIES    426
80       81    Ravichandran Ashwin         INDIA    407
81       82           Haris Sohail      PAKISTAN    400
82       83   Hashmatullah Shahidi   AFGHANISTAN    397
83       84          John Campbell   WEST INDIES    397
84       85             Sam Curran       ENGLAND    396
85       86           Darren Bravo   WEST INDIES    384
86       87          Soumya Sarkar    BANGLADESH    378
87       88            Rahmat Shah   AFGHANISTAN    377
88       90         Mitchell Starc     AUSTRALIA    370
89       91          Cameron Green     AUSTRALIA    368
90       92          Shadman Islam    BANGLADESH    368
91       93           Chris Woakes       ENGLAND    365
92       94          Kieran Powell   WEST INDIES    363
93       95       Mitchell Santner   NEW ZEALAND    355
94       96              Moeen Ali       ENGLAND    348
95       97         Daryl Mitchell   NEW ZEALAND    347
96       98        Joshua Da Silva   WEST INDIES    345
97      100             Ben Foakes       ENGLAND    336

In [9]:
odidf = pd.DataFrame(odibatrankings,columns = ["Position","drop","Player","Country","Rating"])
odidf.drop(columns = ["drop"],axis="columns",inplace=True)
odidf

   Position                 Player               Country Rating
0         1             Babar Azam              PAKISTAN    873
1         2            Virat Kohli                 INDIA    844
2         3           Rohit Sharma                 INDIA    813
3         4            Ross Taylor           NEW ZEALAND    801
4         5            Aaron Finch             AUSTRALIA    779
5         6         Jonny Bairstow               ENGLAND    775
6         7           David Warner             AUSTRALIA    762
7         8        Quinton de Kock          SOUTH AFRICA    758
8         9              Shai Hope           WEST INDIES    758
9        10        Kane Williamson           NEW ZEALAND    754
10       11           Fakhar Zaman              PAKISTAN    741
11       12               Joe Root               ENGLAND    740
12       13        Mushfiqur Rahim            BANGLADESH    723
13       14            Imam-ul-Haq              PAKISTAN    717
14       15         Martin Guptill           NEW ZEALAND    707
15       16         Shikhar Dhawan                 INDIA    704
16       17           Steven Smith             AUSTRALIA    696
17       18              Jason Roy               ENGLAND    687
18       19  Rassie van der Dussen          SOUTH AFRICA    678
19       20          Glenn Maxwell             AUSTRALIA    674
20       21            Tamim Iqbal            BANGLADESH    670
21       22             Alex Carey             AUSTRALIA    669
22       23          Paul Stirling               IRELAND    664
23       24             Ben Stokes               ENGLAND    651
24       25            Eoin Morgan               ENGLAND    650
25       26        Shakib Al Hasan            BANGLADESH    641
26       27               KL Rahul                 INDIA    636
27       28           David Miller          SOUTH AFRICA    632
28       29             Tom Latham           NEW ZEALAND    624
29       30        Nicholas Pooran           WEST INDIES    615
30       31            Jos Buttler               ENGLAND    608
31       32        Shimron Hetmyer           WEST INDIES    607
32       33           Haris Sohail              PAKISTAN    594
33       34         Henry Nicholls           NEW ZEALAND    581
34       35             Aqib Ilyas                  OMAN    578
35       36       Andrew Balbirnie               IRELAND    575
36       37           Kyle Coetzer              SCOTLAND    573
37       38         Brendan Taylor              ZIMBABWE    572
38       39            Mahmudullah            BANGLADESH    571
39       40           Kusal Perera             SRI LANKA    560
40       41            Rahmat Shah           AFGHANISTAN    559
41       42             Evin Lewis           WEST INDIES    558
42       43              Liton Das            BANGLADESH    558
43       44          Sean Williams              ZIMBABWE    553
44       45           Kedar Jadhav                 INDIA    552
45       46         Angelo Mathews             SRI LANKA    550
46       47          Hardik Pandya                 INDIA    548
47       48          Sikandar Raza              ZIMBABWE    540
48       49   Danushka Gunathilaka             SRI LANKA    538
49       50           Kusal Mendis             SRI LANKA    526
50       51             Imad Wasim              PAKISTAN    525
51       52       Avishka Fernando             SRI LANKA    522
52       53          Soumya Sarkar            BANGLADESH    521
53       54         Marcus Stoinis             AUSTRALIA    517
54       55          Calum MacLeod              SCOTLAND    508
55       56    Colin de Grandhomme           NEW ZEALAND    507
56       57      Najibullah Zadran           AFGHANISTAN    506
57       58         Sarfaraz Ahmed              PAKISTAN    504
58       59     Niroshan Dickwella             SRI LANKA    503
59       60   Hashmatullah Shahidi           AFGHANISTAN    498
60       61     Marnus Labuschagne             AUSTRALIA    498
61       62          James Neesham           NEW ZEALAND    495
62       63          Mohammad Nabi           AFGHANISTAN    494
63       64         Mitchell Marsh             AUSTRALIA    489
64       65         Janneman Malan          SOUTH AFRICA    485
65       66          Asghar Afghan           AFGHANISTAN    479
66       67      Richie Berrington              SCOTLAND    479
67       68           Shreyas Iyer                 INDIA    472
68       69         Mohammad Usman  UNITED ARAB EMIRATES    471
69       70    William Porterfield               IRELAND    471
70       71    Dhananjaya de Silva             SRI LANKA    461
71       72       Mitchell Santner           NEW ZEALAND    460
72       73           Craig Ervine              ZIMBABWE    457
73       74           Jason Holder           WEST INDIES    446
74       75          Aiden Markram          SOUTH AFRICA    445
75       76           Temba Bavuma          SOUTH AFRICA    443
76       77       Heinrich Klaasen          SOUTH AFRICA    442
77       78     Andile Phehlukwayo          SOUTH AFRICA    439
78       79             Assad Vala      PAPUA NEW GUINEA    439
79       80      Lahiru Thirimanne             SRI LANKA    436
80       81           Harry Tector               IRELAND    434
81       82        Ravindra Jadeja                 INDIA    434
82       83        Mohammad Mithun            BANGLADESH    433
83       84            Rashid Khan           AFGHANISTAN    432
84       85          George Munsey              SCOTLAND    430
85       86           Rishabh Pant                 INDIA    426
86       87           Matthew Wade             AUSTRALIA    424
87       88          Rovman Powell           WEST INDIES    419
88       89         Curtis Campher               IRELAND    418
89       90          Dasun Shanaka             SRI LANKA    418
90       91       Dinesh Chandimal             SRI LANKA    417
91       92         Kieron Pollard           WEST INDIES    416
92       93          Gulbadin Naib           AFGHANISTAN    415
93       94        Mohammad Rizwan              PAKISTAN    414
94       95               Tony Ura      PAPUA NEW GUINEA    412
95       96              Moeen Ali               ENGLAND    404
96       97      Wanindu Hasaranga             SRI LANKA    403
97       98           Chris Woakes               ENGLAND    403
98       99             Simi Singh               IRELAND    402
99      100          Matthew Cross              SCOTLAND    398

In [10]:
t20df = pd.DataFrame(t20batrankings,columns = ["Position","drop","Player","Country","Rating"])
t20df.drop(columns = ["drop"],axis="columns",inplace=True)
t20df

   Position                 Player               Country Rating
0         1            Dawid Malan               ENGLAND    841
1         2             Babar Azam              PAKISTAN    819
2         3           Devon Conway           NEW ZEALAND    774
3         4            Aaron Finch             AUSTRALIA    733
4         5            Virat Kohli                 INDIA    717
5         6               KL Rahul                 INDIA    699
6         7        Mohammad Rizwan              PAKISTAN    692
7         8         Martin Guptill           NEW ZEALAND    688
8         9             Evin Lewis           WEST INDIES    664
9        10  Rassie van der Dussen          SOUTH AFRICA    650
10       11      Hazratullah Zazai           AFGHANISTAN    636
11       12        Quinton de Kock          SOUTH AFRICA    609
12       13            Eoin Morgan               ENGLAND    599
13       14              Jason Roy               ENGLAND    592
14       15            Colin Munro           NEW ZEALAND    592
15       16            Jos Buttler               ENGLAND    590
16       17         Jonny Bairstow               ENGLAND    588
17       18          George Munsey              SCOTLAND    583
18       19           Rohit Sharma                 INDIA    577
19       20     Rahmanullah Gurbaz           AFGHANISTAN    576
20       21         Mitchell Marsh             AUSTRALIA    575
21       22            Tim Seifert           NEW ZEALAND    573
22       23          Glenn Maxwell             AUSTRALIA    567
23       24          Paul Stirling               IRELAND    566
24       25          Aiden Markram          SOUTH AFRICA    563
25       26         Glenn Phillips           NEW ZEALAND    544
26       28      Richie Berrington              SCOTLAND    542
27       29          Mohammad Naim            BANGLADESH    536
28       30        Reeza Hendricks          SOUTH AFRICA    526
29       31         Shikhar Dhawan                 INDIA    526
30       32          Mohammad Nabi           AFGHANISTAN    523
31       33           David Miller          SOUTH AFRICA    518
32       34            Mahmudullah            BANGLADESH    518
33       35           Shreyas Iyer                 INDIA    516
34       36        Kane Williamson           NEW ZEALAND    512
35       37           Kyle Coetzer              SCOTLAND    511
36       38       Andrew Balbirnie               IRELAND    505
37       39               Tony Ura      PAPUA NEW GUINEA    503
38       40             Ben Cooper           NETHERLANDS    493
39       41      Najibullah Zadran           AFGHANISTAN    492
40       42              Max ODowd           NETHERLANDS    491
41       43          Kevin O Brien               IRELAND    491
42       44          Soumya Sarkar            BANGLADESH    483
43       45          Calum MacLeod              SCOTLAND    483
44       46         Jatinder Singh                  OMAN    482
45       47           Fakhar Zaman              PAKISTAN    481
46       48        Nicholas Pooran           WEST INDIES    481
47       49           Kusal Perera             SRI LANKA    478
48       50       Suryakumar Yadav                 INDIA    477
49       51          Matthew Cross              SCOTLAND    474
50       52          Asghar Afghan           AFGHANISTAN    472
51       53        Shakib Al Hasan            BANGLADESH    469
52       54         Mohammad Usman  UNITED ARAB EMIRATES    458
53       55              Tim David             SINGAPORE    457
54       56              Liton Das            BANGLADESH    449
55       57        Mohammad Hafeez              PAKISTAN    446
56       58            Kamran Khan                 QATAR    445
57       59          Lendl Simmons           WEST INDIES    443
58       60         Kushal Bhurtel                 NEPAL    442
59       61      Ravija Sandaruwan                KUWAIT    435
60       62          Collins Obuya                 KENYA    429
61       63   Danushka Gunathilaka             SRI LANKA    423
62       64        Gerhard Erasmus               NAMIBIA    421
63       66         Faf du Plessis          SOUTH AFRICA    417
64       67         Kieron Pollard           WEST INDIES    417
65       68           Temba Bavuma          SOUTH AFRICA    411
66       69           Nizakat Khan             HONG KONG    405
67       70           D Arcy Short             AUSTRALIA    404
68       71           David Warner             AUSTRALIA    401
69       72        Shimron Hetmyer           WEST INDIES    401
70       73        Zeeshan Maqsood                  OMAN    398
71       74          Sean Williams              ZIMBABWE    396
72       75            Rakep Patel                 KENYA    394
73       76       Heinrich Klaasen          SOUTH AFRICA    393
74       77          Gareth Delany               IRELAND    388
75       78            Ross Taylor           NEW ZEALAND    388
76       79             Finn Allen           NEW ZEALAND    384
77       80           Rishabh Pant                 INDIA    383
78       81       Muhammad Tanveer                 QATAR    382
79       82            Tamim Iqbal            BANGLADESH    381
80       83           Matthew Wade             AUSTRALIA    378
81       84       Navneet Dhaliwal                CANADA    375
82       85           Kusal Mendis             SRI LANKA    373
83       86          Rohan Mustafa  UNITED ARAB EMIRATES    370
84       87            Usman Ghani           AFGHANISTAN    367
85       88              Ryan Burl              ZIMBABWE    366
86       89           Harry Tector               IRELAND    365
87       90           Paras Khadka                 NEPAL    362
88       91             Khawar Ali                  OMAN    360
89       92        Mushfiqur Rahim            BANGLADESH    359
90       93     Ryan ten Doeschate           NETHERLANDS    358
91       94        Gyanendra Malla                 NEPAL    357
92       95           Nitish Kumar                CANADA    356
93       96          Manish Pandey                 INDIA    354
94       97           Steven Smith             AUSTRALIA    352
95       99          Sabbir Rahman            BANGLADESH    345
96      100     Samiullah Shinwari           AFGHANISTAN    344

In [11]:
testbowldf = pd.DataFrame(testbowlrankings,columns = ["Position","drop","Player","Country","Rating"])
testbowldf.drop(columns = ["drop"],axis="columns",inplace=True)
testbowldf

   Position                Player       Country Rating
0         1           Pat Cummins     AUSTRALIA    908
1         2   Ravichandran Ashwin         INDIA    848
2         3           Tim Southee   NEW ZEALAND    824
3         4        Josh Hazlewood     AUSTRALIA    816
4         5           Neil Wagner   NEW ZEALAND    810
5         6        James Anderson       ENGLAND    800
6         7         Kagiso Rabada  SOUTH AFRICA    798
7         8          Stuart Broad       ENGLAND    764
8         9          Jason Holder   WEST INDIES    756
9        10        Jasprit Bumrah         INDIA    754
10       11           Kemar Roach   WEST INDIES    751
11       12        Mitchell Starc     AUSTRALIA    744
12       13           Trent Boult   NEW ZEALAND    738
13       14         Kyle Jamieson   NEW ZEALAND    725
14       15             Hasan Ali      PAKISTAN    723
15       16         Ishant Sharma         INDIA    717
16       17        Mohammad Abbas      PAKISTAN    709
17       18        Shaheen Afridi      PAKISTAN    699
18       19        Mohammed Shami         INDIA    676
19       20           Nathan Lyon     AUSTRALIA    668
20       21       Ravindra Jadeja         INDIA    645
21       22        Suranga Lakmal     SRI LANKA    635
22       23          Mehidy Hasan    BANGLADESH    610
23       24       Shakib Al Hasan    BANGLADESH    605
24       25          Taijul Islam    BANGLADESH    605
25       26          Chris Woakes       ENGLAND    602
26       27       Shannon Gabriel   WEST INDIES    600
27       28        Keshav Maharaj  SOUTH AFRICA    593
28       29           Umesh Yadav         INDIA    579
29       30            Yasir Shah      PAKISTAN    573
30       31         Anrich Nortje  SOUTH AFRICA    564
31       32           Rashid Khan   AFGHANISTAN    543
32       33            Jack Leach       ENGLAND    543
33       34            Axar Patel         INDIA    536
34       35            Ben Stokes       ENGLAND    536
35       36             Moeen Ali       ENGLAND    495
36       37             Mark Wood       ENGLAND    477
37       38        Mohammed Siraj         INDIA    465
38       39       Dilruwan Perera     SRI LANKA    459
39       40         Lahiru Kumara     SRI LANKA    459
40       41    Lasith Embuldeniya     SRI LANKA    444
41       42           Lungi Ngidi  SOUTH AFRICA    436
42       43   Colin de Grandhomme   NEW ZEALAND    424
43       44          Roston Chase   WEST INDIES    423
44       46   Blessing Muzarabani      ZIMBABWE    391
45       47       Vishwa Fernando     SRI LANKA    388
46       48            Nauman Ali      PAKISTAN    387
47       49          Jofra Archer       ENGLAND    383
48       50          Dominic Bess       ENGLAND    381
49       51  Praveen Jayawickrama     SRI LANKA    380
50       52           Kyle Mayers   WEST INDIES    374
51       53          Nayeem Hasan    BANGLADESH    366
52       54            Amir Hamza   AFGHANISTAN    364
53       55        Shardul Thakur         INDIA    357
54       56            Sam Curran       ENGLAND    350
55       57         Kuldeep Yadav         INDIA    348
56       59          Wiaan Mulder  SOUTH AFRICA    333
57       60      Rahkeem Cornwall   WEST INDIES    331
58       61        Jubair Hossain    BANGLADESH    326
59       62             Abu Jayed    BANGLADESH    323
60       63            Ajaz Patel   NEW ZEALAND    320
61       64         Sikandar Raza      ZIMBABWE    315
62       65            Matt Henry   NEW ZEALAND    304
63       66        Alzarri Joseph   WEST INDIES    299
64       67            Olly Stone       ENGLAND    289
65       68         Kasun Rajitha     SRI LANKA    288
66       69        Jomel Warrican   WEST INDIES    281
67       70     Mustafizur Rahman    BANGLADESH    276
68       71         Faheem Ashraf      PAKISTAN    271
69       72        Yamin Ahmadzai   AFGHANISTAN    260
70       73   Dushmantha Chameera     SRI LANKA    248
71       74       Donald Tiripano      ZIMBABWE    248
72       75        Victor Nyauchi      ZIMBABWE    247
73       76           Naseem Shah      PAKISTAN    244
74       77      Mitchell Santner   NEW ZEALAND    237
75       78          Haris Sohail      PAKISTAN    225
76       79          George Linde  SOUTH AFRICA    222
77       80         Dasun Shanaka     SRI LANKA    210
78       81          Taskin Ahmed    BANGLADESH    206
79       82           Mahmudullah    BANGLADESH    205
80       83              Joe Root       ENGLAND    202
81       84         Ramesh Mendis     SRI LANKA    197
82       85           Shadab Khan      PAKISTAN    185
83       86         Sean Williams      ZIMBABWE    181
84       87        Shahbaz Nadeem         INDIA    168
85       88   Dhananjaya de Silva     SRI LANKA    161
86       89     Kraigg Brathwaite   WEST INDIES    133
87       90             Ryan Burl      ZIMBABWE    132
88       91            Zahir Khan   AFGHANISTAN    128
89       92        Angelo Mathews     SRI LANKA    123
90       93         Rubel Hossain    BANGLADESH    122
91       94    Marnus Labuschagne     AUSTRALIA    122
92       95       Kane Williamson   NEW ZEALAND    116
93       96     Washington Sundar         INDIA    107
94       97            Dean Elgar  SOUTH AFRICA    102
95       98        Tendai Chisoro      ZIMBABWE     88
96       99         Navdeep Saini         INDIA     86

In [12]:
odibowldf = pd.DataFrame(odibowlrankings,columns = ["Position","drop","Player","Country","Rating"])
odibowldf.drop(columns = ["drop"],axis="columns",inplace=True)
odibowldf

   Position               Player               Country Rating
0         1          Trent Boult           NEW ZEALAND    737
1         2       Josh Hazlewood             AUSTRALIA    709
2         3     Mujeeb Ur Rahman           AFGHANISTAN    708
3         4         Chris Woakes               ENGLAND    700
4         5         Mehidy Hasan            BANGLADESH    692
5         6           Matt Henry           NEW ZEALAND    691
6         7       Jasprit Bumrah                 INDIA    679
7         8       Mitchell Starc             AUSTRALIA    652
8         9      Shakib Al Hasan            BANGLADESH    650
9        10        Kagiso Rabada          SOUTH AFRICA    648
10       11    Mustafizur Rahman            BANGLADESH    640
11       12          Pat Cummins             AUSTRALIA    636
12       13       Shaheen Afridi              PAKISTAN    630
13       14        Mohammad Amir              PAKISTAN    628
14       15          Rashid Khan           AFGHANISTAN    626
15       16           Adam Zampa             AUSTRALIA    625
16       17    Bhuvneshwar Kumar                 INDIA    621
17       18      Lockie Ferguson           NEW ZEALAND    619
18       19         Jofra Archer               ENGLAND    609
19       20      Akila Dananjaya             SRI LANKA    604
20       21     Yuzvendra Chahal                 INDIA    603
21       22          Lungi Ngidi          SOUTH AFRICA    599
22       23        Mohammad Nabi           AFGHANISTAN    596
23       24            Mark Wood               ENGLAND    594
24       25       Alzarri Joseph           WEST INDIES    592
25       26     Mitchell Santner           NEW ZEALAND    583
26       27       Mohammed Shami                 INDIA    566
27       28        Kuldeep Yadav                 INDIA    562
28       29      Ravindra Jadeja                 INDIA    550
29       30     Sheldon Cottrell           WEST INDIES    541
30       31           Ahmed Raza  UNITED ARAB EMIRATES    531
31       32         Andy McBrine               IRELAND    527
32       33          Shadab Khan              PAKISTAN    517
33       34  Dushmantha Chameera             SRI LANKA    514
34       35    Wanindu Hasaranga             SRI LANKA    508
35       36  Colin de Grandhomme           NEW ZEALAND    508
36       37       Tabraiz Shamsi          SOUTH AFRICA    501
37       38         David Willey               ENGLAND    501
38       39          Tim Southee           NEW ZEALAND    500
39       40   Andile Phehlukwayo          SOUTH AFRICA    497
40       41          Adil Rashid               ENGLAND    497
41       42            Ish Sodhi           NEW ZEALAND    496
42       43            Mark Watt              SCOTLAND    490
43       44           Imad Wasim              PAKISTAN    488
44       45            Hasan Ali              PAKISTAN    483
45       46       Usman Shinwari              PAKISTAN    482
46       47      Jhye Richardson             AUSTRALIA    480
47       48        Rohan Mustafa  UNITED ARAB EMIRATES    477
48       49           Simi Singh               IRELAND    473
49       50     Mashrafe Mortaza            BANGLADESH    469
50       51   Mohammad Saifuddin            BANGLADESH    468
51       52       Safyaan Sharif              SCOTLAND    467
52       53       Tendai Chatara              ZIMBABWE    465
53       54        Nuwan Pradeep             SRI LANKA    459
54       55        James Neesham           NEW ZEALAND    458
55       57         Jason Holder           WEST INDIES    451
56       58            Moeen Ali               ENGLAND    449
57       59           Wahab Riaz              PAKISTAN    447
58       60        Faheem Ashraf              PAKISTAN    445
59       62       Suranga Lakmal             SRI LANKA    443
60       63        Sikandar Raza              ZIMBABWE    440
61       64  Blessing Muzarabani              ZIMBABWE    437
62       65           Tom Curran               ENGLAND    436
63       66          Ashton Agar             AUSTRALIA    436
64       67         Taskin Ahmed            BANGLADESH    434
65       68        Anrich Nortje          SOUTH AFRICA    431
66       69           Josh Davey              SCOTLAND    427
67       71          Craig Young               IRELAND    421
68       72        Sean Williams              ZIMBABWE    420
69       73      Kane Richardson             AUSTRALIA    416
70       74           Ben Stokes               ENGLAND    410
71       75       Shardul Thakur                 INDIA    405
72       76        Rubel Hossain            BANGLADESH    400
73       77        Gulbadin Naib           AFGHANISTAN    399
74       78        Hardik Pandya                 INDIA    394
75       79       Alasdair Evans              SCOTLAND    394
76       80       Keshav Maharaj          SOUTH AFRICA    394
77       81       Barry McCarthy               IRELAND    391
78       82       Mitchell Marsh             AUSTRALIA    390
79       83  Dhananjaya de Silva             SRI LANKA    388
80       84       Marcus Stoinis             AUSTRALIA    377
81       85     Lakshan Sandakan             SRI LANKA    376
82       86         Taijul Islam            BANGLADESH    374
83       87       Mohammad Nawaz              PAKISTAN    370
84       88      Donald Tiripano              ZIMBABWE    367
85       89           Assad Vala      PAPUA NEW GUINEA    361
86       90        Fred Klaassen           NETHERLANDS    358
87       91      George Dockrell               IRELAND    357
88       92        Oshane Thomas           WEST INDIES    355
89       93        Kyle Jamieson           NEW ZEALAND    352
90       94        Michael Leask              SCOTLAND    351
91       95      Zeeshan Maqsood                  OMAN    350
92       96   Sharafuddin Ashraf           AFGHANISTAN    347
93       97         Roston Chase           WEST INDIES    347
94       98           Bilal Khan                  OMAN    344
95       99  Saurabh Netravalkar         UNITED STATES    343
96      100         Norman Vanua      PAPUA NEW GUINEA    342

In [13]:
t20bowldf = pd.DataFrame(t20bowlrankings,columns = ["Position","drop","Player","Country","Rating"])
t20bowldf.drop(columns = ["drop"],axis="columns",inplace=True)
t20bowldf

   Position                Player               Country Rating
0         1        Tabraiz Shamsi          SOUTH AFRICA    792
1         2     Wanindu Hasaranga             SRI LANKA    764
2         3           Rashid Khan           AFGHANISTAN    719
3         4           Adil Rashid               ENGLAND    689
4         5      Mujeeb Ur Rahman           AFGHANISTAN    687
5         6           Tim Southee           NEW ZEALAND    669
6         7           Ashton Agar             AUSTRALIA    649
7         8            Adam Zampa             AUSTRALIA    648
8         9             Ish Sodhi           NEW ZEALAND    640
9        10     Mustafizur Rahman            BANGLADESH    619
10       11      Mitchell Santner           NEW ZEALAND    616
11       12       Shakib Al Hasan            BANGLADESH    610
12       13             Mark Watt              SCOTLAND    595
13       14     Bhuvneshwar Kumar                 INDIA    594
14       15          Chris Jordan               ENGLAND    579
15       16      Lakshan Sandakan             SRI LANKA    574
16       17          Fabian Allen           WEST INDIES    572
17       18             Mark Wood               ENGLAND    563
18       19     Washington Sundar                 INDIA    562
19       20   Dushmantha Chameera             SRI LANKA    555
20       21         Mohammad Nabi           AFGHANISTAN    546
21       22      Sheldon Cottrell           WEST INDIES    546
22       23        Shaheen Afridi              PAKISTAN    543
23       24      Yuzvendra Chahal                 INDIA    529
24       25        Alasdair Evans              SCOTLAND    529
25       26           Karim Janat           AFGHANISTAN    527
26       27          George Linde          SOUTH AFRICA    524
27       28   Blessing Muzarabani              ZIMBABWE    522
28       29            Bilal Khan                  OMAN    521
29       30       Lockie Ferguson           NEW ZEALAND    515
30       31        Shardul Thakur                 INDIA    508
31       33        Jasprit Bumrah                 INDIA    504
32       34        Josh Hazlewood             AUSTRALIA    502
33       35       Kane Richardson             AUSTRALIA    501
34       36       Akila Dananjaya             SRI LANKA    501
35       37         Faheem Ashraf              PAKISTAN    498
36       38         Deepak Chahar                 INDIA    497
37       39          Jofra Archer               ENGLAND    495
38       40            Mark Adair               IRELAND    495
39       41           Lungi Ngidi          SOUTH AFRICA    487
40       42            Imad Wasim              PAKISTAN    484
41       43    Mohammad Saifuddin            BANGLADESH    479
42       44           Shadab Khan              PAKISTAN    478
43       45           Trent Boult           NEW ZEALAND    473
44       46        Mitchell Starc             AUSTRALIA    472
45       47            Tom Curran               ENGLAND    468
46       48          David Willey               ENGLAND    468
47       49            Haris Rauf              PAKISTAN    467
48       50          Dwayne Bravo           WEST INDIES    467
49       51        Safyaan Sharif              SCOTLAND    466
50       52            Ahmed Raza  UNITED ARAB EMIRATES    463
51       53  Roelof van der Merwe           NETHERLANDS    463
52       54            Sam Curran               ENGLAND    462
53       55          Jason Holder           WEST INDIES    456
54       56     Paul van Meekeren           NETHERLANDS    454
55       57      Beuran Hendricks          SOUTH AFRICA    453
56       58       Bernard Scholtz               NAMIBIA    452
57       59        Lasith Malinga             SRI LANKA    450
58       60        Brandon Glover           NETHERLANDS    449
59       61    Andile Phehlukwayo          SOUTH AFRICA    449
60       62      Mohammad Hasnain              PAKISTAN    446
61       63             Hasan Ali              PAKISTAN    446
62       64            Shem Obado                 KENYA    444
63       65            Khawar Ali                  OMAN    442
64       67        Mohammad Nawaz              PAKISTAN    440
65       68          Norman Vanua      PAPUA NEW GUINEA    437
66       70        Pieter Seelaar           NETHERLANDS    436
67       71            Andrew Tye             AUSTRALIA    428
68       72       Mohammad Nadeem                  OMAN    420
69       73            Simi Singh               IRELAND    414
70       74         Rohan Mustafa  UNITED ARAB EMIRATES    412
71       75  Wellington Masakadza              ZIMBABWE    410
72       77    Sandeep Lamichhane                 NEPAL    405
73       78          Sultan Ahmed  UNITED ARAB EMIRATES    405
74       79         Kagiso Rabada          SOUTH AFRICA    404
75       80           Pat Cummins             AUSTRALIA    403
76       81            Josh Davey              SCOTLAND    403
77       82         Kuldeep Yadav                 INDIA    399
78       83         Hardik Pandya                 INDIA    393
79       84         Krunal Pandya                 INDIA    390
80       85         Gareth Delany               IRELAND    389
81       86   Timm van der Gugten           NETHERLANDS    389
82       87           Isuru Udana             SRI LANKA    389
83       88           Zahoor Khan  UNITED ARAB EMIRATES    386
84       89         Fred Klaassen           NETHERLANDS    383
85       90         Charles Amini      PAPUA NEW GUINEA    381
86       91        Billy Stanlake             AUSTRALIA    379
87       93         Naveen-ul-Haq           AFGHANISTAN    378
88       94       Al-Amin Hossain            BANGLADESH    378
89       95           Hamza Tahir              SCOTLAND    373
90       96           Usman Qadir              PAKISTAN    371
91       97            Ehsan Khan             HONG KONG    371
92       98         Anrich Nortje          SOUTH AFRICA    370
93       99        Nosaina Pokana      PAPUA NEW GUINEA    367
94      100            Ben Stokes               ENGLAND    362

In [14]:
testalldf = pd.DataFrame(testallrankings,columns = ["Position","drop","Player","Country","Rating"])
testalldf.drop(columns = ["drop"],axis="columns",inplace=True)
testalldf

  Position               Player      Country Rating
0        1         Jason Holder  WEST INDIES    414
1        2           Ben Stokes      ENGLAND    362
2        3      Ravindra Jadeja        INDIA    359
3        4  Ravichandran Ashwin        INDIA    345
4        5      Shakib Al Hasan   BANGLADESH    334
5        6        Kyle Jamieson  NEW ZEALAND    311
6        7       Mitchell Starc    AUSTRALIA    275
7        8          Pat Cummins    AUSTRALIA    249
8        9  Colin de Grandhomme  NEW ZEALAND    232
9       10         Chris Woakes      ENGLAND    219

In [15]:
odialldf = pd.DataFrame(odiallrankings,columns = ["Position","drop","Player","Country","Rating"])
odialldf.drop(columns = ["drop"],axis="columns",inplace=True)
odialldf

  Position               Player      Country Rating
0        1      Shakib Al Hasan   BANGLADESH    416
1        2        Mohammad Nabi  AFGHANISTAN    294
2        3         Chris Woakes      ENGLAND    282
3        4          Rashid Khan  AFGHANISTAN    270
4        5     Mitchell Santner  NEW ZEALAND    268
5        6           Ben Stokes      ENGLAND    266
6        7  Colin de Grandhomme  NEW ZEALAND    257
7        8           Imad Wasim     PAKISTAN    256
8        9      Ravindra Jadeja        INDIA    238
9       10        Sikandar Raza     ZIMBABWE    237

In [16]:
t20alldf = pd.DataFrame(t20allrankings,columns = ["Position","drop","Player","Country","Rating"])
t20alldf.drop(columns = ["drop"],axis="columns",inplace=True)
t20alldf

  Position             Player               Country Rating
0        1    Shakib Al Hasan            BANGLADESH    286
1        2      Mohammad Nabi           AFGHANISTAN    285
2        3  Richie Berrington              SCOTLAND    194
3        4         Khawar Ali                  OMAN    159
4        5      Collins Obuya                 KENYA    153
5        6      Rohan Mustafa  UNITED ARAB EMIRATES    152
6        7      Glenn Maxwell             AUSTRALIA    151
7        8      Gareth Delany               IRELAND    150
8        9     Mitchell Marsh             AUSTRALIA    141
9       10      Sean Williams              ZIMBABWE    140

In [17]:
testteamdf = pd.DataFrame(testteam,columns = ["Position","Team","Rating","Points"])
testteamdf

  Position          Team Rating Points
0        1   NEW ZEALAND    126   2764
1        2         INDIA    119   2987
2        3     AUSTRALIA    108   1844
3        4       ENGLAND    107   3753
4        5      PAKISTAN     94   2247
5        6  SOUTH AFRICA     88   1675
6        7   WEST INDIES     78   2114
7        8     SRI LANKA     78   2095
8        9    BANGLADESH     49    779
9       10      ZIMBABWE     31    342

In [18]:
oditeamdf = pd.DataFrame(oditeam,columns = ["Position","Team","Rating","Points"])
oditeamdf

   Position              Team Rating Points
0         1       NEW ZEALAND    121   2054
1         2           ENGLAND    119   3793
2         3         AUSTRALIA    116   3244
3         4             INDIA    113   3624
4         5      SOUTH AFRICA    103   2267
5         6          PAKISTAN     93   2524
6         7        BANGLADESH     91   2639
7         8       WEST INDIES     84   2523
8         9         SRI LANKA     79   2303
9        10       AFGHANISTAN     62   1054
10       11       NETHERLANDS     48    336
11       12           IRELAND     46   1067
12       13          ZIMBABWE     38    646
13       14          SCOTLAND     37    258
14       15              OMAN     34    240
15       16             NEPAL     24    119
16       17               UAE     21    190
17       18           NAMIBIA     16     97
18       19     UNITED STATES     12     93
19       20  PAPUA NEW GUINEA      0      0

In [19]:
t20teamdf = pd.DataFrame(t20team,columns = ["Position","Team","Rating","Points"])
t20teamdf

   Position              Team Rating Points
0         1           ENGLAND    278   7786
1         2             INDIA    273   7093
2         3       NEW ZEALAND    263   6048
3         4          PAKISTAN    261   8883
4         5      SOUTH AFRICA    246   6640
5         6         AUSTRALIA    240   7923
6         7       AFGHANISTAN    236   2826
7         8         SRI LANKA    235   4456
8         9       WEST INDIES    234   6792
9        10        BANGLADESH    234   4915
10       11          ZIMBABWE    193   4249
11       12             NEPAL    187   3556
12       13           IRELAND    187   3921
13       14          SCOTLAND    185   2035
14       15               UAE    184   2023
15       16  PAPUA NEW GUINEA    179   2501
16       17       NETHERLANDS    175   3504
17       18              OMAN    173   1732
18       19           NAMIBIA    157   2204
19       20         SINGAPORE    140   1678
20       21             QATAR    129   1422
21       22            CANADA    126   1263
22       23         HONG KONG    121   1572
23       24            JERSEY    114   1481
24       25             KENYA    112    894
25       26             ITALY    111    663
26       27            KUWAIT    108    866
27       28      SAUDI ARABIA    107    428
28       29           DENMARK    101    606
29       30           BERMUDA     95    568
30       31          MALAYSIA     86   1723
31       32            UGANDA     85    847
32       33           GERMANY     84    759
33       34     UNITED STATES     81    644
34       35          BOTSWANA     79    786
35       36           NIGERIA     75    375
36       37          GUERNSEY     72    645
37       39           AUSTRIA     65    650
38       41             SPAIN     57    457
39       42           BAHRAIN     57    227
40       43           BELGIUM     56    502
41       44          TANZANIA     56    167
42       45       PHILIPPINES     48    241
43       46            MEXICO     45    313
44       48           VANUATU     44    435
45       49            BELIZE     42    209
46       50         ARGENTINA     41    206
47       51              PERU     36    179
48       52              FIJI     35    105
49       53            MALAWI     35    312
50       54            PANAMA     32    162
51       55             SAMOA     32    159
52       56             JAPAN     32    126
53       57        COSTA RICA     32    126
54       58             MALTA     31    214
55       59        LUXEMBOURG     30    358
56       60          THAILAND     25    175
57       61          BULGARIA     24    313
58       62          PORTUGAL     24    119
59       63    CZECH REPUBLIC     22    356
60       64           FINLAND     21    106
61       65       SOUTH KOREA     20     78
62       66        MOZAMBIQUE     19    175
63       67       ISLE OF MAN     19     77
64       69            BHUTAN     12     47
65       70          MALDIVES      9     65
66       71      SAINT HELENA      9     55
67       72            BRAZIL      8     39
68       73             CHILE      4     19
69       74         GIBRALTAR      3     13
70       75           MYANMAR      0      1
71       76         INDONESIA      0      0
72       77           LESOTHO      0      0
73       78            RWANDA      0      0
74       81             CHINA      0      0

In [20]:
writer = pd.ExcelWriter(r'C:\Users\krthg\OneDrive\Documents\Merit\PythonAssignments\Rankings\batting.xlsx', engine="openpyxl")
testdf.to_excel(writer,sheet_name = "batting-test")
odidf.to_excel(writer,sheet_name = "batting-odi")
t20df.to_excel(writer,sheet_name = "batting-t20")
writer.save()
writer.close()

In [21]:
writer = pd.ExcelWriter(r'C:\Users\krthg\OneDrive\Documents\Merit\PythonAssignments\Rankings\bowling.xlsx', engine="openpyxl")
testbowldf.to_excel(writer,sheet_name = "bowling-test")
odibowldf.to_excel(writer,sheet_name = "bowling-odi")
t20bowldf.to_excel(writer,sheet_name = "bowling-t20")
writer.save()
writer.close()

In [22]:
writer = pd.ExcelWriter(r'C:\Users\krthg\OneDrive\Documents\Merit\PythonAssignments\Rankings\allrounders.xlsx', engine="openpyxl")
testalldf.to_excel(writer,sheet_name = "allrounder-test")
odialldf.to_excel(writer,sheet_name = "allrounder-odi")
t20alldf.to_excel(writer,sheet_name = "allrounder-t20")
writer.save()
writer.close()

In [23]:
writer = pd.ExcelWriter(r'C:\Users\krthg\OneDrive\Documents\Merit\PythonAssignments\Rankings\team.xlsx', engine="openpyxl")
testteamdf.to_excel(writer,sheet_name = "team-test")
oditeamdf.to_excel(writer,sheet_name = "team-odi")
t20teamdf.to_excel(writer,sheet_name = "team-t20")
writer.save()
writer.close()